#!/usr/bin/env node
// Generates fixtures/sheets-by-rep.ts: the doc-comments mockup's spreadsheet
// (reports/q3-sales-by-rep.xlsx) — the promo's Q3 rows plus a second "By rep"
// tab, so cell comments can be shown naming their sheet ("By rep · B4").
// Kept apart from make.mjs so regenerating this never rewrites the landing
// promo's two workbooks. Run from desktop/:
//   node src/renderer/dev/workbench/fixtures/sheets/make-by-rep.mjs
import pkg from 'exceljs';
const { Workbook } = pkg;
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROWS = [
  ['West', 'Priya', 128, 'Jul'], ['East', 'Marcus', 96, 'Jul'], ['North', 'Lena', 41, 'Jul'],
  ['South', 'Diego', 151, 'Jul'], ['Central', 'Aisha', 88, 'Jul'], ['West', 'Priya', 112, 'Aug'],
  ['East', 'Marcus', 134, 'Aug'], ['North', 'Lena', 57, 'Aug'], ['South', 'Diego', 122, 'Aug'],
  ['Central', 'Aisha', 91, 'Aug'], ['West', 'Priya', 143, 'Sep'], ['East', 'Marcus', 108, 'Sep'],
  ['North', 'Lena', 63, 'Sep'], ['South', 'Diego', 167, 'Sep'], ['Central', 'Aisha', 99, 'Sep'],
];

const wb = new Workbook();
const q3 = wb.addWorksheet('Q3');
q3.columns = [{ width: 12 }, { width: 12 }, { width: 10 }, { width: 8 }];
q3.addRow(['Region', 'Rep', 'Amount', 'Month']).font = { bold: true };
for (const r of ROWS) q3.addRow(r);

// Rep order Priya, Marcus, Lena… so Lena's total lands in B4 (the seed comment).
const byRep = wb.addWorksheet('By rep');
byRep.columns = [{ width: 12 }, { width: 12 }];
byRep.addRow(['Rep', 'Q3 total']).font = { bold: true };
for (const rep of ['Priya', 'Marcus', 'Lena', 'Diego', 'Aisha']) {
  byRep.addRow([rep, ROWS.filter((r) => r[1] === rep).reduce((a, r) => a + r[2], 0)]);
}

const b64 = Buffer.from(await wb.xlsx.writeBuffer()).toString('base64');
const out = `// GENERATED by fixtures/sheets/make-by-rep.mjs — do not edit. The doc-comments
// mockup's two-tab workbook (Q3 + By rep), base64 for the workbench.
export const SHEET_BY_REP = '${b64}';
`;
writeFileSync(join(dirname(fileURLToPath(import.meta.url)), '..', 'sheets-by-rep.ts'), out);
console.log('wrote fixtures/sheets-by-rep.ts');
