import { readFileSync } from 'fs';
import { join } from 'path';
import { describe, it, expect } from 'vitest';

// WHY these Android guards live in the DESKTOP suite: it is the only suite that runs
// on every change (scripts/verify.sh); Gradle only runs when someone builds the phone
// app. Each line below pins a fix from the 2026-09-10 Android parity audit that had
// silently shipped broken for months because nothing checked it.
// Test file is at desktop/tests/, so two levels up reaches the repo root.
const ROOT = join(__dirname, '..', '..');
const read = (...p: string[]) => readFileSync(join(ROOT, ...p), 'utf8');

describe('Android builds tell the truth about themselves', () => {
  it('requests POST_NOTIFICATIONS at runtime, not just in the manifest', () => {
    // Declared since the approval channel was added, never requested: on Android 13+
    // every notification (including the approval prompt) was dropped silently.
    const manifest = read('app', 'src', 'main', 'AndroidManifest.xml');
    const activity = read('app', 'src', 'main', 'kotlin', 'com', 'youcoded', 'app', 'MainActivity.kt');
    expect(manifest).toContain('android.permission.POST_NOTIFICATIONS');
    expect(activity).toContain('permission.POST_NOTIFICATIONS');
    expect(activity).toContain('notificationPermissionLauncher.launch(');
  });

  it('only advertises the arm64 ABI the bootstrap runtime ships for', () => {
    // Native libs from ML Kit / zstd / the terminal JNI used to make the APK claim all
    // four ABIs; it installed on 32-bit and x86 phones and died at first-run setup.
    const gradle = read('app', 'build.gradle.kts');
    expect(gradle).toMatch(/abiFilters\s*\+=\s*listOf\("arm64-v8a"\)/);
  });

  it('tracks nothing under the generated web bundle folder', () => {
    // A tracked index.html from April referenced chunk hashes no build produced and
    // carried the keyboard-overlay bug the live source had fixed; the folder is
    // regenerated by Gradle's bundleWebUi before every APK.
    const gitignore = read('.gitignore');
    expect(gitignore).toContain('app/src/main/assets/web/');
    expect(gitignore).not.toContain('!app/src/main/assets/web/index.html');
  });

  it('stamps the version in CI so a beta is never identical to the last release', () => {
    // Every beta APK on GitHub carried versionCode 20 / "1.2.4" — the May release's
    // identity — so a phone could not tell a beta was newer.
    const workflow = read('.github', 'workflows', 'android-release.yml');
    expect(workflow).toContain('name: Stamp version');
    expect(workflow).toMatch(/versionCode = \$\{CODE\}/);
    expect(workflow).toMatch(/100 \+ \$\{\{ github\.run_number \}\}/);
  });
});
