// Pins T10 of the doc-comments build (docs/active/specs/2026-09-26-doc-
// comments-build-design.md §3.2, §8): reading Word comments off a REAL
// .docx's comments.xml/commentsExtended.xml parts, in the Electron main
// process, with no renderer/mammoth/jsdom involved.
//
// Fixtures: tests/fixtures/doc-comments/{launch-brief,no-comments}.docx,
// generated by tests/fixtures/doc-comments/make-docx-fixtures.mjs (see that
// file's header for exactly how and why). Both are real archives assembled
// with jszip from hand-written OOXML matching Word's own schema — the same
// approach and jszip version the doc-comments MOCK's own fixture generator
// already used (src/renderer/dev/workbench/fixtures/docs/make.mjs).
import { describe, it, expect } from 'vitest';
import { readFile } from 'fs/promises';
import { join } from 'path';
import { readDocxComments } from '../src/main/doc-comments/docx-comments';

const FIXTURES_DIR = join(__dirname, 'fixtures', 'doc-comments');

async function loadFixture(name: string): Promise<Buffer> {
  return readFile(join(FIXTURES_DIR, name));
}

// §3.2 (review 1, F1 — blocker): this module must run with no browser DOM at
// all — Electron's main process has none. This file deliberately carries NO
// per-file environment override comment (other test files opt into a DOM
// environment with one, naming it directly would itself trip vitest's
// docblock scanner — it matches that magic comment anywhere in a file, not
// just as a real directive, which is exactly what broke this test the first
// time it was written) — the absence of one IS the pin: vitest's default
// environment here is 'node' (vitest.config.ts), so a global `DOMParser`
// existing at all in this file would mean something upstream silently pulled
// in a DOM environment, which is exactly the renderer-only assumption F1
// found and corrected.
describe('docx-comments — runs in a plain Node environment, not a renderer/jsdom one', () => {
  it('has no global DOMParser (the same fact that ruled out a renderer-side implementation)', () => {
    expect(typeof (globalThis as { DOMParser?: unknown }).DOMParser).toBe('undefined');
  });
});

describe('docx-comments — parsing the launch-brief fixture', () => {
  it('reads both top-level comments with their authors, text and resolved state', async () => {
    const bytes = await loadFixture('launch-brief.docx');
    const result = await readDocxComments(bytes, 'docs/launch-brief.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.comments).toHaveLength(2);

    const goalComment = result.comments.find((c) => c.text.startsWith('Is 30% realistic'));
    expect(goalComment).toBeDefined();
    expect(goalComment?.author).toBe('person:Priya Shah');
    expect(goalComment?.resolved).toBe(true); // w15:done="1"
    expect(goalComment?.replies).toEqual([]);
    expect(goalComment?.path).toBe('docs/launch-brief.docx');
    if (goalComment?.selector.kind === 'text') {
      expect(goalComment.selector.selector.exact).toBe(
        'Move 30% of weekly active users to the new app within six weeks of launch.'
      );
    } else {
      throw new Error('expected a text selector');
    }
  });

  it('reconstructs a reply thread via w15:paraIdParent', async () => {
    const bytes = await loadFixture('launch-brief.docx');
    const result = await readDocxComments(bytes, 'docs/launch-brief.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const timelineComment = result.comments.find((c) => c.text.startsWith('Legal needs the beta terms'));
    expect(timelineComment).toBeDefined();
    expect(timelineComment?.resolved).toBe(false); // w15:done="0"
    expect(timelineComment?.replies).toHaveLength(1);
    expect(timelineComment?.replies[0]).toMatchObject({
      author: 'person:Marcus Lee',
      text: 'Confirmed with legal — the beta terms are ready as of this morning.',
    });
    // Account-ready id shape (§1.2): `${commentId}-r${n}`.
    expect(timelineComment?.replies[0].id).toBe(`${timelineComment?.id}-r1`);
    // The reply itself is never a separate top-level record.
    expect(result.comments).not.toContainEqual(expect.objectContaining({ text: expect.stringContaining('Confirmed with legal') }));
  });

  it('builds a TextQuoteSelector with prefix/suffix context around the ranged text', async () => {
    const bytes = await loadFixture('launch-brief.docx');
    const result = await readDocxComments(bytes, 'docs/launch-brief.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const c = result.comments.find((c) => c.text.startsWith('Legal needs'));
    if (c?.selector.kind !== 'text') throw new Error('expected a text selector');
    expect(c.selector.selector.exact).toBe('Beta opens to 500 customers on March 10');
    // Comes right after the "Timeline" heading paragraph in the fixture body.
    expect(c.selector.selector.prefix.length).toBeGreaterThan(0);
    expect(c.selector.selector.suffix).toContain(', with the public launch');
  });
});

describe('docx-comments — a docx with no comments.xml part', () => {
  it('returns an empty list, never a crash', async () => {
    const bytes = await loadFixture('no-comments.docx');
    const result = await readDocxComments(bytes, 'docs/no-comments.docx');
    expect(result).toEqual({ ok: true, comments: [] });
  });
});

describe('docx-comments — not a valid zip at all', () => {
  it('refuses honestly instead of throwing', async () => {
    const result = await readDocxComments(Buffer.from('not a docx'), 'docs/garbage.docx');
    expect(result).toEqual({ ok: false, error: 'invalid-docx' });
  });
});
