// Pins T10 of the doc-comments build (docs/active/specs/2026-09-26-doc-
// comments-build-design.md §3.2, §8): reading Word comments off a REAL
// .docx's comments.xml/commentsExtended.xml parts, in the Electron main
// process, with no renderer/mammoth/jsdom involved.
//
// Fixtures: tests/fixtures/doc-comments/{launch-brief,no-comments,spanning-
// comment,deeply-nested}.docx, generated by tests/fixtures/doc-comments/
// make-docx-fixtures.mjs (see that file's header for exactly how and why).
// All are real archives assembled with jszip from hand-written OOXML
// matching Word's own schema — the same approach and jszip version the
// doc-comments MOCK's own fixture generator already used
// (src/renderer/dev/workbench/fixtures/docs/make.mjs).
import { describe, it, expect } from 'vitest';
import { readFile, writeFile, mkdtemp, rm, stat } from 'fs/promises';
import { join } from 'path';
import { tmpdir } from 'os';
import JSZip from 'jszip';
import {
  readDocxComments,
  addDocxComment,
  replyToDocxComment,
  resolveDocxComment,
  reopenDocxComment,
  moveDocxComment,
  writeDocxMutation,
  DOCX_BACKUP_SUFFIX,
} from '../src/main/doc-comments/docx-comments';
import { backupPathFor } from '../src/main/doc-comments/write-pipeline';
import { buildDeclaredOversizeZip, buildRealZipBomb, buildCorruptedEntryZip } from './fixtures/doc-comments/oversized-zip';
import type { CommentSelector } from '../src/shared/doc-comments-types';

async function exists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

const FIXTURES_DIR = join(__dirname, 'fixtures', 'doc-comments');

async function loadFixture(name: string): Promise<Buffer> {
  return readFile(join(FIXTURES_DIR, name));
}

function textSelector(exact: string): CommentSelector {
  return { kind: 'text', selector: { type: 'TextQuoteSelector', exact, prefix: '', suffix: '', occurrence: 0 } };
}

async function withScratchCopy<T>(fixtureName: string, fn: (targetPath: string) => Promise<T>): Promise<T> {
  const dir = await mkdtemp(join(tmpdir(), 'ycd-docx-write-'));
  const target = join(dir, fixtureName);
  await writeFile(target, await loadFixture(fixtureName));
  try {
    return await fn(target);
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}

/**
 * T11's own "gapped/non-sequential existing w:id" fixture (§8 T11's pinning
 * test list) — built in-memory rather than as a new checked-in binary,
 * since it exists only to pin `maxExistingCommentId`'s "(max existing w:id)
 * + 1, never assumed monotonic" rule (§3.3, F6) and needs no other content
 * T10's own fixtures don't already cover. Two comments, ids 3 and 7 (a gap,
 * and starting above 0) — a naive `comments.length` counter would mint `2`
 * next; the correct next id is `8`.
 */
const W = 'xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"';
const W14 = 'xmlns:w14="http://schemas.microsoft.com/office/word/2010/wordml"';

async function buildGappedIdsDocx(): Promise<Buffer> {
  const zip = new JSZip();
  zip.file(
    '[Content_Types].xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/><Override PartName="/word/comments.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.comments+xml"/></Types>`
  );
  zip.file(
    '_rels/.rels',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>`
  );
  zip.file(
    'word/_rels/document.xml.rels',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/comments" Target="comments.xml"/></Relationships>`
  );
  zip.file(
    'word/document.xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document ${W} ${W14}><w:body>` +
      `<w:p w14:paraId="E0000001"><w:commentRangeStart w:id="3"/><w:r><w:t xml:space="preserve">First commented run.</w:t></w:r><w:commentRangeEnd w:id="3"/><w:r><w:rPr><w:rStyle w:val="CommentReference"/></w:rPr><w:commentReference w:id="3"/></w:r></w:p>` +
      `<w:p w14:paraId="E0000002"><w:commentRangeStart w:id="7"/><w:r><w:t xml:space="preserve">Second commented run.</w:t></w:r><w:commentRangeEnd w:id="7"/><w:r><w:rPr><w:rStyle w:val="CommentReference"/></w:rPr><w:commentReference w:id="7"/></w:r></w:p>` +
      `<w:p w14:paraId="E0000003"><w:r><w:t xml:space="preserve">A brand new sentence with nothing commented yet.</w:t></w:r></w:p>` +
      `</w:body></w:document>`
  );
  zip.file(
    'word/comments.xml',
    `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:comments ${W} ${W14}>` +
      `<w:comment w:id="3" w:author="Priya Shah" w:date="2026-09-26T09:00:00Z"><w:p w14:paraId="F0000003"><w:r><w:t xml:space="preserve">First note.</w:t></w:r></w:p></w:comment>` +
      `<w:comment w:id="7" w:author="Priya Shah" w:date="2026-09-26T09:01:00Z"><w:p w14:paraId="F0000007"><w:r><w:t xml:space="preserve">Second note.</w:t></w:r></w:p></w:comment>` +
      `</w:comments>`
  );
  return zip.generateAsync({ type: 'nodebuffer' });
}

// §3.2 (review 1, F1 — blocker): this module must run with no browser DOM at
// all — Electron's main process has none. This file deliberately carries NO
// per-file environment override comment (other test files opt into a DOM
// environment with one, naming it directly would itself trip vitest's
// docblock scanner — it matches that magic comment anywhere in a file, not
// just as a real directive, which is exactly what broke this test the first
// time it was written) — the absence of one IS the pin: vitest's default
// environment here is 'node' (vitest.config.ts), so a global `DOMParser`
// existing at all in this file would mean something upstream silently pulled
// in a DOM environment, which is exactly the renderer-only assumption F1
// found and corrected.
describe('docx-comments — runs in a plain Node environment, not a renderer/jsdom one', () => {
  it('has no global DOMParser (the same fact that ruled out a renderer-side implementation)', () => {
    expect(typeof (globalThis as { DOMParser?: unknown }).DOMParser).toBe('undefined');
  });
});

describe('docx-comments — parsing the launch-brief fixture', () => {
  it('reads both top-level comments with their authors, text and resolved state', async () => {
    const bytes = await loadFixture('launch-brief.docx');
    const result = await readDocxComments(bytes, 'docs/launch-brief.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.comments).toHaveLength(2);

    const goalComment = result.comments.find((c) => c.text.startsWith('Is 30% realistic'));
    expect(goalComment).toBeDefined();
    expect(goalComment?.author).toBe('person:Priya Shah');
    expect(goalComment?.resolved).toBe(true); // w15:done="1"
    expect(goalComment?.replies).toEqual([]);
    expect(goalComment?.path).toBe('docs/launch-brief.docx');
    if (goalComment?.selector.kind === 'text') {
      expect(goalComment.selector.selector.exact).toBe(
        'Move 30% of weekly active users to the new app within six weeks of launch.'
      );
    } else {
      throw new Error('expected a text selector');
    }
  });

  it('reconstructs a reply thread via w15:paraIdParent', async () => {
    const bytes = await loadFixture('launch-brief.docx');
    const result = await readDocxComments(bytes, 'docs/launch-brief.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const timelineComment = result.comments.find((c) => c.text.startsWith('Legal needs the beta terms'));
    expect(timelineComment).toBeDefined();
    expect(timelineComment?.resolved).toBe(false); // w15:done="0"
    expect(timelineComment?.replies).toHaveLength(1);
    expect(timelineComment?.replies[0]).toMatchObject({
      author: 'person:Marcus Lee',
      text: 'Confirmed with legal — the beta terms are ready as of this morning.',
    });
    // Account-ready id shape (§1.2): `${commentId}-r${n}`.
    expect(timelineComment?.replies[0].id).toBe(`${timelineComment?.id}-r1`);
    // The reply itself is never a separate top-level record.
    expect(result.comments).not.toContainEqual(expect.objectContaining({ text: expect.stringContaining('Confirmed with legal') }));
  });

  it('builds a TextQuoteSelector with prefix/suffix context around the ranged text', async () => {
    const bytes = await loadFixture('launch-brief.docx');
    const result = await readDocxComments(bytes, 'docs/launch-brief.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const c = result.comments.find((c) => c.text.startsWith('Legal needs'));
    if (c?.selector.kind !== 'text') throw new Error('expected a text selector');
    expect(c.selector.selector.exact).toBe('Beta opens to 500 customers on March 10');
    // Comes right after the "Timeline" heading paragraph in the fixture body.
    expect(c.selector.selector.prefix.length).toBeGreaterThan(0);
    expect(c.selector.selector.suffix).toContain(', with the public launch');
  });
});

describe('docx-comments — a docx with no comments.xml part', () => {
  it('returns an empty list, never a crash', async () => {
    const bytes = await loadFixture('no-comments.docx');
    const result = await readDocxComments(bytes, 'docs/no-comments.docx');
    expect(result).toEqual({ ok: true, comments: [] });
  });
});

describe('docx-comments — not a valid zip at all', () => {
  it('refuses honestly instead of throwing', async () => {
    const result = await readDocxComments(Buffer.from('not a docx'), 'docs/garbage.docx');
    expect(result).toEqual({ ok: false, error: 'invalid-docx' });
  });
});

// Implementation-review F2 (major): a decompression-bomb-shaped archive must
// be refused BEFORE any entry is decompressed. `buildDeclaredOversizeZip`
// builds a real, tiny zip whose central-directory metadata falsely declares
// a huge uncompressed size for one entry — the actual compressed bytes stay
// a few dozen bytes, so this test never allocates anywhere near the declared
// size itself; it only proves the guard trips on the declared metadata.
// WHY a named budget: this file's one genuinely heavy test builds AND decompresses a real
// 201 MB zip bomb (2.3 s alone, measured 2026-09-28). Under `verify.sh --full` every other
// check runs at once and wall time inflates several-fold past the 30 s suite default;
// 120 s is ~50x the alone measurement. (test-suite-hygiene.md: named, measured budgets.)
const REAL_ZIP_BOMB_BUDGET_MS = 120_000;

describe('docx-comments — a decompression-bomb-shaped archive', () => {
  it('refuses word/comments.xml declaring an implausible uncompressed size', async () => {
    const bytes = await buildDeclaredOversizeZip(
      { 'word/document.xml': '<w:document><w:body/></w:document>', 'word/comments.xml': '<w:comments/>' },
      'word/comments.xml',
      500 * 1024 * 1024
    );
    const result = await readDocxComments(bytes, 'docs/bomb.docx');
    expect(result).toEqual({ ok: false, error: 'archive-too-large' });
  });

  it('refuses word/document.xml declaring an implausible uncompressed size', async () => {
    const bytes = await buildDeclaredOversizeZip(
      { 'word/document.xml': '<w:document><w:body/></w:document>', 'word/comments.xml': '<w:comments/>' },
      'word/document.xml',
      500 * 1024 * 1024
    );
    const result = await readDocxComments(bytes, 'docs/bomb.docx');
    expect(result).toEqual({ ok: false, error: 'archive-too-large' });
  });

  // F3 (implementation review): a declared-size lie isn't the only shape a
  // decompression bomb can take — an entry whose declared size is small (or
  // never checked at all here) but whose REAL decompressed bytes exceed the
  // ceiling must be caught too, by `decompressBounded`'s own byte-counting
  // loop (zip-size-guard.ts), never by trusting the archive's metadata. This
  // is a REAL zip bomb (word/comments.xml genuinely decompresses to just over
  // the 200MB ceiling) — no central-directory patching involved at all.
  it('refuses word/comments.xml whose REAL decompressed bytes exceed the ceiling, with no declared-size lie involved', async () => {
    const bytes = await buildRealZipBomb(
      { 'word/document.xml': '<w:document><w:body/></w:document>' },
      'word/comments.xml',
      201 * 1024 * 1024
    );
    const result = await readDocxComments(bytes, 'docs/real-bomb.docx');
    expect(result).toEqual({ ok: false, error: 'archive-too-large' });
  }, REAL_ZIP_BOMB_BUDGET_MS);

  // Code review 2026-09-27, desktop F2: a truncated/corrupted entry has
  // NOTHING to do with size and must not come back as 'archive-too-large' —
  // that code now means only a genuine overflow (the two tests above). This
  // scrambles word/comments.xml's own compressed bytes (never its declared
  // size), so `decompressBounded`'s stream 'error' event fires — proves it
  // maps to this module's own 'invalid-docx', matching `readDocxComments`'s
  // existing "not a docx at all" case just above.
  it("a genuinely corrupted word/comments.xml entry reports 'invalid-docx', never 'archive-too-large'", async () => {
    const bytes = await buildCorruptedEntryZip(
      { 'word/document.xml': '<w:document><w:body/></w:document>', 'word/comments.xml': '<w:comments><w:comment w:id="0"/></w:comments>' },
      'word/comments.xml',
    );
    const result = await readDocxComments(bytes, 'docs/corrupt.docx');
    expect(result).toEqual({ ok: false, error: 'invalid-docx' });
  });
});

// Implementation-review F3 (the recursion-depth guard): a comment buried
// thousands of levels deep inside nested w:sdt/w:sdtContent wrappers must
// still be found — a recursive visit()-per-element walk (the pre-fix shape)
// overflows the call stack long before this depth (confirmed empirically
// while building this fixture: a plain recursive tree walk in this Node
// overflows under 5,000 levels), while the fixed iterative walk has no such
// ceiling.
describe('docx-comments — a comment nested thousands of levels deep', () => {
  it('finds it without overflowing the call stack', async () => {
    const bytes = await loadFixture('deeply-nested.docx');
    const result = await readDocxComments(bytes, 'docs/deeply-nested.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.comments).toHaveLength(1);
    expect(result.comments[0].text).toBe('A comment buried very deep in the document tree.');
    if (result.comments[0].selector.kind !== 'text') throw new Error('expected a text selector');
    expect(result.comments[0].selector.selector.exact).toBe('A comment buried very deep in the document tree.');
  });
});

// Implementation-review F6: a comment range split across multiple runs
// (formatting boundaries) AND across two paragraphs — every other fixture in
// this file happens to use a single-run, single-paragraph range, which never
// exercised this.
describe('docx-comments — a comment spanning multiple runs and two paragraphs', () => {
  it('captures the exact quote across the paragraph break, with correct prefix/suffix', async () => {
    const bytes = await loadFixture('spanning-comment.docx');
    const result = await readDocxComments(bytes, 'docs/spanning-comment.docx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.comments).toHaveLength(1);
    const c = result.comments[0];
    expect(c.text).toBe('Should this be one paragraph instead of two?');
    if (c.selector.kind !== 'text') throw new Error('expected a text selector');
    // The exact quote spans the paragraph break: text from two runs in
    // paragraph 1, the paragraph-break newline, then text from two more runs
    // in paragraph 2.
    expect(c.selector.selector.exact).toBe('first half \nsecond half.');
    expect(c.selector.selector.prefix).toContain('Before the change:');
    expect(c.selector.selector.suffix).toContain('After the note.');
  });
});

// =============================================================================
// T11: writing (add / reply / resolve / reopen / move) — docs/active/specs/
// 2026-09-26-doc-comments-build-design.md §3.3, §8 T11.
// =============================================================================

describe('docx-comments write — add', () => {
  it('adds a new comment and it round-trips through the SAME reader', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: textSelector('Marketing emails go out the same morning as the public launch.'),
        text: 'Confirm the send time with marketing.',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.id).toMatch(/^w-\d+$/);

      const read = await readDocxComments(await readFile(target), 'docs/launch-brief.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      const added = read.comments.find((c) => c.id === result.id);
      expect(added).toBeDefined();
      expect(added?.text).toBe('Confirm the send time with marketing.');
      expect(added?.author).toBe('person:You');
      expect(added?.resolved).toBe(false);
      if (added?.selector.kind !== 'text') throw new Error('expected a text selector');
      expect(added.selector.selector.exact).toBe('Marketing emails go out the same morning as the public launch.');

      // Existing Word-authored comments are preserved byte-for-byte in their
      // OWN fields (comments.xml's <w:comment> entries for ids 0/1/2 are
      // untouched by an add elsewhere in the document).
      const untouched = read.comments.find((c) => c.id === 'w-0');
      expect(untouched).toMatchObject({ author: 'person:Priya Shah', resolved: true, text: expect.stringContaining('Is 30% realistic') });
    });
  });

  it('creates comments.xml (+ its content-types override + relationship) from scratch for a docx with no comments part yet', async () => {
    await withScratchCopy('no-comments.docx', async (target) => {
      const before = await readFile(target);
      const zipBefore = await JSZip.loadAsync(before);
      expect(zipBefore.file('word/comments.xml')).toBeNull();

      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/no-comments.docx',
        selector: textSelector('Nothing here has ever been commented on.'),
        text: 'First comment this file has ever had.',
        author: 'assistant',
      });
      expect(result.ok).toBe(true);

      const after = await readFile(target);
      const zipAfter = await JSZip.loadAsync(after);
      expect(zipAfter.file('word/comments.xml')).not.toBeNull();
      const contentTypes = await zipAfter.file('[Content_Types].xml')!.async('string');
      expect(contentTypes).toContain('/word/comments.xml');
      const rels = await zipAfter.file('word/_rels/document.xml.rels')!.async('string');
      expect(rels).toContain('comments.xml');

      const read = await readDocxComments(after, 'docs/no-comments.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      expect(read.comments).toHaveLength(1);
      expect(read.comments[0].author).toBe('person:Assistant');
      expect(read.comments[0].text).toBe('First comment this file has ever had.');
    });
  });

  it('a comment spanning multiple runs and two paragraphs inserts correctly around an EXISTING range', async () => {
    await withScratchCopy('spanning-comment.docx', async (target) => {
      // Targets "half \nsecond" — spans the "half " run, the paragraph
      // break, and the start of "second " in the NEXT paragraph — distinct
      // from the fixture's own existing id=5 range, proving this insertion
      // doesn't get confused by markers already present in the document.
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/spanning-comment.docx',
        selector: textSelector('half \nsecond'),
        text: 'A second, independent multi-paragraph comment.',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;

      const read = await readDocxComments(await readFile(target), 'docs/spanning-comment.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      expect(read.comments).toHaveLength(2);
      const added = read.comments.find((c) => c.id === result.id);
      if (added?.selector.kind !== 'text') throw new Error('expected a text selector');
      expect(added.selector.selector.exact).toBe('half \nsecond');
      // The ORIGINAL comment (id 5) is untouched.
      const original = read.comments.find((c) => c.id === 'w-5');
      expect(original?.text).toBe('Should this be one paragraph instead of two?');
      if (original?.selector.kind !== 'text') throw new Error('expected a text selector');
      expect(original.selector.selector.exact).toBe('first half \nsecond half.');
    });
  });

  it('a comment on text strictly INSIDE a single run splits that run correctly', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      // "30%" sits in the middle of the w:t "Move 30% of weekly active
      // users..." — neither offset lands on a run boundary, so this only
      // passes if splitRunAtOffsets's mid-run split is correct.
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: textSelector('30%'),
        text: 'Just the percentage.',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;

      const read = await readDocxComments(await readFile(target), 'docs/launch-brief.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      const added = read.comments.find((c) => c.id === result.id);
      if (added?.selector.kind !== 'text') throw new Error('expected a text selector');
      expect(added.selector.selector.exact).toBe('30%');
      expect(added.selector.selector.prefix).toContain('Move');
      expect(added.selector.selector.suffix).toContain('of weekly');
      // The pre-existing comment on the SAME paragraph (id 0, the whole
      // goal sentence) is unaffected by another comment's run split.
      const original = read.comments.find((c) => c.id === 'w-0');
      if (original?.selector.kind !== 'text') throw new Error('expected a text selector');
      expect(original.selector.selector.exact).toBe('Move 30% of weekly active users to the new app within six weeks of launch.');
    });
  });

  it('mints (max existing w:id) + 1 against a gapped/non-sequential id set, never a naive count-based id', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'ycd-docx-write-'));
    const target = join(dir, 'gapped.docx');
    await writeFile(target, await buildGappedIdsDocx());
    try {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/gapped.docx',
        selector: textSelector('A brand new sentence with nothing commented yet.'),
        text: 'x',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      expect(result.id).toBe('w-8'); // existing ids are 3 and 7 — next is 8, not 2
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('refuses a selector that does not resolve against the current text', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const before = await readFile(target);
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: textSelector('this text does not exist anywhere in the document'),
        text: 'x',
        author: 'user',
      });
      expect(result).toEqual({ ok: false, error: 'selector-not-found' });
      expect(await readFile(target)).toEqual(before); // untouched — nothing was even attempted
    });
  });

  it('refuses a cell selector against a Word target rather than silently coercing it', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: { kind: 'cell', selector: { type: 'CellSelector', cell: 'A1' } },
        text: 'x',
        author: 'user',
      });
      expect(result).toEqual({ ok: false, error: 'invalid-selector' });
    });
  });
});

// Originally (commit ffda4b654, xlsx T12/T13 review F1) this REFUSED text
// containing an XML 1.0-illegal control character, since writing one raw
// into `<w:t>` produced invalid XML this app's own verify step couldn't
// catch. Changed 2026-09-27 to STRIP those characters instead — a user has
// no way to see or remove one (it arrives via paste), so a refusal they
// can't act on is worse than silently dropping an invisible byte.
describe('docx-comments write — strips XML-illegal control characters from comment text', () => {
  it('strips illegal control characters from an added comment and returns the persisted text', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: textSelector('Marketing emails go out the same morning as the public launch.'),
        text: 'before\x01\x02\x1Fafter',
        author: 'user',
      });
      expect(result).toEqual({ ok: true, id: expect.any(String), text: 'beforeafter' });

      const read = await readDocxComments(await readFile(target), 'docs/launch-brief.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      const added = read.comments.find((c) => result.ok && c.id === result.id);
      expect(added?.text).toBe('beforeafter');
    });
  });

  it('strips illegal control characters from a reply for the same reason', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await replyToDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        id: 'w-0',
        text: 'x\x00y',
        author: 'user',
      });
      expect(result).toEqual({ ok: true, reply: { id: expect.any(String), author: 'user', text: 'xy', createdAt: expect.any(Number) } });
    });
  });

  it('still allows tab, newline and carriage return in comment text', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: textSelector('Marketing emails go out the same morning as the public launch.'),
        text: 'line one\nline two\ttabbed\rcr',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (result.ok) expect(result.text).toBe('line one\nline two\ttabbed\rcr');
    });
  });
});

describe('docx-comments write — reply', () => {
  it('appends a reply, preserving the existing reply thread', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await replyToDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        id: 'w-1',
        text: 'Sounds good, thanks both.',
        author: 'user',
      });
      // T5 review (design §1.6, F2): `reply`'s response is enriched to carry
      // the real persisted `CommentReply` — its own `author` is the CALLER'S
      // original `CommentAuthor` value ('user'), not the round-tripped Word
      // display name ('person:You') `readDocxComments` maps it to on the way
      // back OUT of the file — this is what lets the renderer's optimistic
      // entry (also 'user') be swapped in place without changing how it
      // renders.
      expect(result).toEqual({
        ok: true,
        reply: { id: 'w-1-r2', author: 'user', text: 'Sounds good, thanks both.', createdAt: expect.any(Number) },
      });

      const read = await readDocxComments(await readFile(target), 'docs/launch-brief.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      const target1 = read.comments.find((c) => c.id === 'w-1');
      expect(target1?.replies).toHaveLength(2);
      expect(target1?.replies[0]).toMatchObject({ author: 'person:Marcus Lee' }); // the ORIGINAL reply, unmoved
      expect(target1?.replies[1]).toMatchObject({ author: 'person:You', text: 'Sounds good, thanks both.' });
      // The enriched response's own id matches what the read path independently computes for it.
      expect(target1?.replies[1].id).toBe((result as any).reply.id);
    });
  });

  it('refuses an id this file does not have', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await replyToDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-999', text: 'x', author: 'user' });
      expect(result).toEqual({ ok: false, error: 'comment-not-found' });
    });
  });
});

describe('docx-comments write — resolve / reopen', () => {
  it('resolve sets w15:done, reopen clears it, and either creates commentsExtended.xml if the file never had one', async () => {
    await withScratchCopy('spanning-comment.docx', async (target) => {
      const zipBefore = await JSZip.loadAsync(await readFile(target));
      expect(zipBefore.file('word/commentsExtended.xml')).toBeNull();

      const resolved = await resolveDocxComment({ absolutePath: target, path: 'docs/spanning-comment.docx', id: 'w-5' });
      expect(resolved).toEqual({ ok: true });
      let read = await readDocxComments(await readFile(target), 'docs/spanning-comment.docx');
      expect(read.ok && read.comments[0].resolved).toBe(true);

      const reopened = await reopenDocxComment({ absolutePath: target, path: 'docs/spanning-comment.docx', id: 'w-5' });
      expect(reopened).toEqual({ ok: true });
      read = await readDocxComments(await readFile(target), 'docs/spanning-comment.docx');
      expect(read.ok && read.comments[0].resolved).toBe(false);
    });
  });

  it('resolving an already-resolved comment updates the EXISTING entry rather than duplicating it', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      // id 0 starts resolved (w15:done="1") — reopen then resolve again.
      await reopenDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-0' });
      await resolveDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-0' });
      const zip = await JSZip.loadAsync(await readFile(target));
      const extendedXml = await zip.file('word/commentsExtended.xml')!.async('string');
      expect((extendedXml.match(/w15:paraId="10000000"/g) ?? []).length).toBe(1); // still exactly one entry
      const read = await readDocxComments(await readFile(target), 'docs/launch-brief.docx');
      expect(read.ok && read.comments.find((c) => c.id === 'w-0')?.resolved).toBe(true);
      // Unrelated entries (id 1, id 2's reply-linking) are untouched.
      const t1 = read.ok ? read.comments.find((c) => c.id === 'w-1') : undefined;
      expect(t1?.resolved).toBe(false);
      expect(t1?.replies).toHaveLength(1);
    });
  });

  it('refuses an id this file does not have', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await resolveDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-999' });
      expect(result).toEqual({ ok: false, error: 'comment-not-found' });
    });
  });
});

describe('docx-comments write — move', () => {
  it('relocates a comment: the OLD range is gone, the NEW one resolves, id/replies/resolve state unchanged', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await moveDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        id: 'w-1',
        newSelector: textSelector('Keep support tickets about the update below 200 per week.'),
      });
      expect(result).toEqual({ ok: true });

      const bytes = await readFile(target);
      const zip = await JSZip.loadAsync(bytes);
      const documentXml = await zip.file('word/document.xml')!.async('string');
      // OLD range gone: the moved-away text no longer carries id 1's markers.
      expect(documentXml).not.toMatch(/Beta opens to 500 customers[\s\S]{0,80}w:id="1"/);
      expect((documentXml.match(/w:commentRangeStart w:id="1"/g) ?? []).length).toBe(1);
      expect((documentXml.match(/w:commentRangeEnd w:id="1"/g) ?? []).length).toBe(1);
      expect((documentXml.match(/w:commentReference w:id="1"/g) ?? []).length).toBe(1);

      const read = await readDocxComments(bytes, 'docs/launch-brief.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      const moved = read.comments.find((c) => c.id === 'w-1');
      expect(moved).toBeDefined();
      if (moved?.selector.kind !== 'text') throw new Error('expected a text selector');
      expect(moved.selector.selector.exact).toBe('Keep support tickets about the update below 200 per week.');
      // id/replies/resolve state carried over unchanged.
      expect(moved.replies).toHaveLength(1);
      expect(moved.replies[0]).toMatchObject({ author: 'person:Marcus Lee' });
      expect(moved.resolved).toBe(false);
    });
  });

  it('refuses when newSelector does not resolve, leaving the file byte-identical (never a silent delete)', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const before = await readFile(target);
      const result = await moveDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        id: 'w-1',
        newSelector: textSelector('this text is nowhere in the document'),
      });
      expect(result).toEqual({ ok: false, error: 'selector-not-found' });
      expect(await readFile(target)).toEqual(before);
    });
  });

  it('refuses an id this file does not have', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await moveDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        id: 'w-999',
        newSelector: textSelector('Keep support tickets'),
      });
      expect(result).toEqual({ ok: false, error: 'comment-not-found' });
    });
  });
});

// T11 follow-up (design §3.3's new step 0, design review round 3 F4): this
// task shipped before step 0 existed in the design, so the write path it
// built had no such check at all — now added, and pinned here through
// `addDocxComment` itself (not just the shared write-pipeline.ts unit tests)
// to prove it reaches a REAL docx write, exactly the way §3.3 step 0's own
// "implemented once, in write-pipeline.ts's shared entry point" claim
// promises.
describe('docx-comments write — refuses a file open elsewhere in real Word/LibreOffice before backup', () => {
  it('refuses \'file-open-elsewhere\' before touching the backup or the target when a Word owner file (~$<name>.docx) sits beside it', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const dir = target.slice(0, target.lastIndexOf('/'));
      const base = target.slice(target.lastIndexOf('/') + 1);
      const ownerFile = join(dir, `~$${base}`);
      await writeFile(ownerFile, 'destin');
      const before = await readFile(target);
      const backupPath = backupPathFor(target, DOCX_BACKUP_SUFFIX);
      const result = await addDocxComment({
        absolutePath: target, path: 'docs/launch-brief.docx',
        selector: { kind: 'text', selector: { type: 'TextQuoteSelector', exact: 'Marketing emails go out', prefix: '', suffix: '', occurrence: 0 } },
        text: 'x', author: 'user',
      });
      expect(result).toEqual({ ok: false, error: 'file-open-elsewhere' });
      expect(await exists(backupPath)).toBe(false); // never even reached step 1 (backup)
      expect(await readFile(target)).toEqual(before); // the target itself is untouched
    });
  });

  it('refuses \'file-open-elsewhere\' when a LibreOffice lock file (.~lock.<name>.docx#) sits beside it', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const dir = target.slice(0, target.lastIndexOf('/'));
      const base = target.slice(target.lastIndexOf('/') + 1);
      const lockFile = join(dir, `.~lock.${base}#`);
      await writeFile(lockFile, ',destin,localhost,01-01-2026 00:00,file:///home/destin;');
      const result = await replyToDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-0', text: 'x', author: 'user' });
      expect(result).toEqual({ ok: false, error: 'file-open-elsewhere' });
    });
  });

  it('proceeds normally once the owner file is gone (the common "since closed it" case)', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const dir = target.slice(0, target.lastIndexOf('/'));
      const base = target.slice(target.lastIndexOf('/') + 1);
      const ownerFile = join(dir, `~$${base}`);
      await writeFile(ownerFile, 'destin');
      const first = await resolveDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-0' });
      expect(first).toEqual({ ok: false, error: 'file-open-elsewhere' });
      await rm(ownerFile, { force: true });
      const retry = await resolveDocxComment({ absolutePath: target, path: 'docs/launch-brief.docx', id: 'w-0' });
      expect(retry).toEqual({ ok: true });
    });
  });
});

describe('docx-comments write — verify-after-write with automatic rollback', () => {
  // Exercises `writeDocxMutation` directly — the SAME shared pipeline every
  // real operation above (`addDocxComment` etc.) calls — with an injected
  // fault (a `verify` that deliberately returns `false`), per T11's own
  // pinning test list: "failed verification restores the original (inject a
  // fault)". This is more direct than corrupting real bytes on disk to
  // provoke a genuine failure.
  //
  // F5 (T11 review — major): the backup no longer lives NEXT TO the source
  // file (a sibling `.docx.bak-<timestamp>`, which a project's own git repo
  // or cloud-sync folder would pick up) — it's one ROLLING file at a stable,
  // hashed path under `~/.claude/youcoded-doc-backups/` (write-pipeline.ts's
  // `backupPathFor`), kept after a successful write rather than deleted. These
  // two tests were rewritten against that new location and lifecycle; see
  // `write-pipeline.ts` for the actual behaviour they pin.
  it('a failed verification restores the original bytes exactly, and clears the backup it consumed', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const before = await readFile(target);
      const backupPath = backupPathFor(target, DOCX_BACKUP_SUFFIX);
      const result = await writeDocxMutation(
        target,
        async (bytes) => ({ ok: true, bytes: Buffer.concat([bytes, Buffer.from([0])]) }),
        async () => false // the injected fault: verification always fails
      );
      expect(result).toEqual({ ok: false, error: 'verify-failed' });
      expect(await readFile(target)).toEqual(before); // restored byte-for-byte
      // Rolled back means RENAMED back over the target — the backup file
      // itself no longer exists afterward (it now IS the live file again).
      expect(await exists(backupPath)).toBe(false);
    });
  });

  it('the backup exists WHILE verify runs, and is KEPT (not deleted) after a successful write', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const backupPath = backupPathFor(target, DOCX_BACKUP_SUFFIX);
      const before = await readFile(target);
      let sawBackupDuringVerify = false;
      const result = await writeDocxMutation(
        target,
        async (bytes) => ({ ok: true, bytes: Buffer.concat([bytes]) }),
        async () => {
          sawBackupDuringVerify = await exists(backupPath);
          return true;
        }
      );
      expect(result).toEqual({ ok: true });
      expect(sawBackupDuringVerify).toBe(true); // existed DURING the write
      expect(await exists(backupPath)).toBe(true); // KEPT after success (F5)
      expect(await readFile(backupPath)).toEqual(before); // holds the PRE-write bytes
    });
  });

  it('one rolling backup per file — a second successful write overwrites the same backup path, never adding a second one', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      // `backupPathFor` is a pure hash of `target`'s own absolute path, so
      // "never adding a second one" is exactly "the path is the SAME both
      // times" (asserted directly, not by counting a shared directory other
      // tests' own backups also live in) — what actually needs proving is
      // that its CONTENT rolls forward to the latest pre-write bytes rather
      // than staying frozen at the first write's.
      const backupPathFirst = backupPathFor(target, DOCX_BACKUP_SUFFIX);
      const firstOriginal = await readFile(target);
      await writeDocxMutation(target, async (bytes) => ({ ok: true, bytes }), async () => true);
      expect(await readFile(backupPathFirst)).toEqual(firstOriginal);

      const secondOriginal = await readFile(target);
      const result = await writeDocxMutation(
        target,
        async (bytes) => ({ ok: true, bytes: Buffer.concat([bytes, Buffer.from([1])]) }),
        async () => true
      );
      expect(result).toEqual({ ok: true });
      const backupPathSecond = backupPathFor(target, DOCX_BACKUP_SUFFIX);
      expect(backupPathSecond).toBe(backupPathFirst); // same stable path, both times
      // The backup now reflects the SECOND write's pre-write bytes — the
      // first write's backup was overwritten in place, never left as a
      // second file.
      expect(await readFile(backupPathSecond)).toEqual(secondOriginal);
    });
  });
});

describe('docx-comments write — concurrency', () => {
  it('two mutations on one file serialize, and neither is lost', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const [a, b] = await Promise.all([
        addDocxComment({
          absolutePath: target,
          path: 'docs/launch-brief.docx',
          selector: textSelector('Marketing emails go out the same morning as the public launch.'),
          text: 'First concurrent comment.',
          author: 'user',
        }),
        addDocxComment({
          absolutePath: target,
          path: 'docs/launch-brief.docx',
          selector: textSelector('The payment screen has not been tested on older Android phones.'),
          text: 'Second concurrent comment.',
          author: 'assistant',
        }),
      ]);
      expect(a.ok).toBe(true);
      expect(b.ok).toBe(true);
      if (!a.ok || !b.ok) return;
      expect(a.id).not.toBe(b.id); // unique ids even when minted concurrently

      const read = await readDocxComments(await readFile(target), 'docs/launch-brief.docx');
      expect(read.ok).toBe(true);
      if (!read.ok) return;
      // Original 2 top-level comments + both concurrent adds — NEITHER lost.
      expect(read.comments).toHaveLength(4);
      expect(read.comments.some((c) => c.text === 'First concurrent comment.')).toBe(true);
      expect(read.comments.some((c) => c.text === 'Second concurrent comment.')).toBe(true);
    });
  });
});

// -----------------------------------------------------------------------
// T11 review round — F1/F2/F3/F4, all against `word365-realistic.docx`
// (tests/fixtures/doc-comments/make-docx-fixtures.mjs's own header explains
// exactly what it carries and why: a dangling hyperlink r:id, rsid-bearing
// runs, and existing commentsIds.xml/commentsExtensible.xml parts — "a
// fixture that looks like a real Word 365 file", per the review's own ask).
// -----------------------------------------------------------------------

/** Order-INDEPENDENT attribute lookup — linkedom does not guarantee it
 *  serializes attributes in setAttribute call order (confirmed empirically:
 *  a clone built by copying a parsed element's own attributes in iteration
 *  order came back reversed), so a test asserting on a specific attribute's
 *  VALUE must never assume where it sits in the tag. */
function attr(tag: string, name: string): string | null {
  const m = new RegExp(`${name}="([^"]*)"`).exec(tag);
  return m ? m[1] : null;
}

function selfClosingTags(xml: string, tagName: string): string[] {
  return xml.match(new RegExp(`<${tagName}\\b[^>]*/>`, 'g')) ?? [];
}

function findCommentBlock(commentsXml: string, rawId: string): string | null {
  const blocks = commentsXml.match(/<w:comment\b[^>]*>[\s\S]*?<\/w:comment>/g) ?? [];
  return blocks.find((b) => attr(b, 'w:id') === rawId) ?? null;
}

describe('docx-comments write — F1: a pre-existing dangling relationship never blocks an unrelated write', () => {
  it('adding a comment elsewhere succeeds despite a dangling hyperlink r:id, which is left completely untouched', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const before = await readFile(target);
      const documentXmlBefore = await (await JSZip.loadAsync(before)).file('word/document.xml')!.async('string');
      const hyperlinkMarkup = '<w:hyperlink r:id="rId99"><w:r><w:t xml:space="preserve">External reference</w:t></w:r></w:hyperlink>';
      expect(documentXmlBefore).toContain(hyperlinkMarkup); // the dangling ref really is there

      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/word365-realistic.docx',
        selector: textSelector('look strong across every region'),
        text: 'Which regions specifically?',
        author: 'user',
      });
      // The OLD behaviour: `verifyOoxmlWiring` judged the WHOLE document, so
      // this write would fail with 'verify-failed' purely because of a
      // relationship this operation never went near.
      expect(result.ok).toBe(true);
      if (!result.ok) return;

      const documentXmlAfter = await (await JSZip.loadAsync(await readFile(target))).file('word/document.xml')!.async('string');
      expect(documentXmlAfter).toContain(hyperlinkMarkup); // still there, byte-for-byte, untouched
    });
  });
});

describe('docx-comments write — F2: a part this operation never touches round-trips byte-identical', () => {
  it('resolve changes only commentsExtended.xml; document.xml, comments.xml, [Content_Types].xml and the rels part are byte-identical', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const zipBefore = await JSZip.loadAsync(await readFile(target));
      const [documentBefore, commentsBefore, contentTypesBefore, relsBefore] = await Promise.all([
        zipBefore.file('word/document.xml')!.async('string'),
        zipBefore.file('word/comments.xml')!.async('string'),
        zipBefore.file('[Content_Types].xml')!.async('string'),
        zipBefore.file('word/_rels/document.xml.rels')!.async('string'),
      ]);

      const result = await resolveDocxComment({ absolutePath: target, path: 'docs/word365-realistic.docx', id: 'w-0' });
      expect(result.ok).toBe(true);

      const zipAfter = await JSZip.loadAsync(await readFile(target));
      expect(await zipAfter.file('word/document.xml')!.async('string')).toBe(documentBefore);
      expect(await zipAfter.file('word/comments.xml')!.async('string')).toBe(commentsBefore);
      expect(await zipAfter.file('[Content_Types].xml')!.async('string')).toBe(contentTypesBefore);
      expect(await zipAfter.file('word/_rels/document.xml.rels')!.async('string')).toBe(relsBefore);
      expect(await zipAfter.file('word/commentsExtended.xml')!.async('string')).toContain('w15:done="1"');
    });
  });

  it('reopen changes only commentsExtended.xml the same way', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      await resolveDocxComment({ absolutePath: target, path: 'docs/word365-realistic.docx', id: 'w-0' });
      const zipBefore = await JSZip.loadAsync(await readFile(target));
      const [documentBefore, commentsBefore, contentTypesBefore, relsBefore] = await Promise.all([
        zipBefore.file('word/document.xml')!.async('string'),
        zipBefore.file('word/comments.xml')!.async('string'),
        zipBefore.file('[Content_Types].xml')!.async('string'),
        zipBefore.file('word/_rels/document.xml.rels')!.async('string'),
      ]);

      const result = await reopenDocxComment({ absolutePath: target, path: 'docs/word365-realistic.docx', id: 'w-0' });
      expect(result.ok).toBe(true);

      const zipAfter = await JSZip.loadAsync(await readFile(target));
      expect(await zipAfter.file('word/document.xml')!.async('string')).toBe(documentBefore);
      expect(await zipAfter.file('word/comments.xml')!.async('string')).toBe(commentsBefore);
      expect(await zipAfter.file('[Content_Types].xml')!.async('string')).toBe(contentTypesBefore);
      expect(await zipAfter.file('word/_rels/document.xml.rels')!.async('string')).toBe(relsBefore);
      expect(await zipAfter.file('word/commentsExtended.xml')!.async('string')).toContain('w15:done="0"');
    });
  });

  it('reply changes only comments.xml and commentsExtended.xml; document.xml, [Content_Types].xml and rels are byte-identical', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const zipBefore = await JSZip.loadAsync(await readFile(target));
      const [documentBefore, contentTypesBefore, relsBefore] = await Promise.all([
        zipBefore.file('word/document.xml')!.async('string'),
        zipBefore.file('[Content_Types].xml')!.async('string'),
        zipBefore.file('word/_rels/document.xml.rels')!.async('string'),
      ]);

      const result = await replyToDocxComment({
        absolutePath: target,
        path: 'docs/word365-realistic.docx',
        id: 'w-0',
        text: 'Broken out by region in the appendix.',
        author: 'user',
      });
      expect(result.ok).toBe(true);

      const zipAfter = await JSZip.loadAsync(await readFile(target));
      expect(await zipAfter.file('word/document.xml')!.async('string')).toBe(documentBefore);
      expect(await zipAfter.file('[Content_Types].xml')!.async('string')).toBe(contentTypesBefore);
      expect(await zipAfter.file('word/_rels/document.xml.rels')!.async('string')).toBe(relsBefore);
      const commentsAfter = await zipAfter.file('word/comments.xml')!.async('string');
      expect(commentsAfter).toContain('Broken out by region in the appendix.');
    });
  });

  it('add changes only document.xml (new range markers + reference run) and comments.xml — [Content_Types].xml and rels stay byte-identical since comments.xml already existed', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const zipBefore = await JSZip.loadAsync(await readFile(target));
      const [documentBefore, contentTypesBefore, relsBefore] = await Promise.all([
        zipBefore.file('word/document.xml')!.async('string'),
        zipBefore.file('[Content_Types].xml')!.async('string'),
        zipBefore.file('word/_rels/document.xml.rels')!.async('string'),
      ]);

      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/word365-realistic.docx',
        // The WHOLE run, start-to-end (unlike F3's test below, which targets
        // a strictly-interior substring on purpose) — both edges land on
        // leaf BOUNDARIES, so `insertCommentRangeMarkers` never needs to
        // split the run at all, and the only diff against `documentBefore`
        // is exactly the three marker/reference substrings this normalized
        // comparison strips.
        selector: textSelector('The results look strong across every region this cycle, well ahead of plan.'),
        text: 'Which regions specifically?',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      const newId = result.id.slice('w-'.length);

      const zipAfter = await JSZip.loadAsync(await readFile(target));
      expect(await zipAfter.file('[Content_Types].xml')!.async('string')).toBe(contentTypesBefore);
      expect(await zipAfter.file('word/_rels/document.xml.rels')!.async('string')).toBe(relsBefore);

      const documentAfter = await zipAfter.file('word/document.xml')!.async('string');
      // A NORMALIZED diff (F2's own ask): strip exactly the three substrings
      // this add is known to insert and nothing else should remain different.
      const normalized = documentAfter
        .replace(`<w:commentRangeStart w:id="${newId}"/>`, '')
        .replace(`<w:commentRangeEnd w:id="${newId}"/>`, '')
        .replace(`<w:r><w:rPr><w:rStyle w:val="CommentReference"/></w:rPr><w:commentReference w:id="${newId}"/></w:r>`, '');
      expect(normalized).toBe(documentBefore);
    });
  });
});

describe('docx-comments write — F3: splitting a run preserves its own attributes (rsids)', () => {
  it('a comment strictly inside an rsid-bearing run keeps w:rsidR/w:rsidRDefault on every resulting piece', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/word365-realistic.docx',
        // Strictly inside the "The results look strong across every region
        // this cycle, well ahead of plan." run — forces a 3-way split
        // (before / quote / after), all from the SAME original <w:r
        // w:rsidR="00CC5678" w:rsidRDefault="00CC5678">.
        selector: textSelector('look strong across every region'),
        text: 'Which regions specifically?',
        author: 'user',
      });
      expect(result.ok).toBe(true);

      const documentXml = await (await JSZip.loadAsync(await readFile(target))).file('word/document.xml')!.async('string');
      // Prior behaviour (F3): `splitRunAtOffsets` only cloned the run's
      // `w:rPr` child, silently dropping every attribute Word stamps
      // directly on `<w:r>` — every split piece would have NEITHER rsid.
      const rsidRRuns = (documentXml.match(/<w:r\b[^>]*>/g) ?? []).filter((tag) => attr(tag, 'w:rsidR') === '00CC5678');
      const rsidRDefaultRuns = (documentXml.match(/<w:r\b[^>]*>/g) ?? []).filter(
        (tag) => attr(tag, 'w:rsidRDefault') === '00CC5678'
      );
      expect(rsidRRuns).toHaveLength(3); // before / quote / after
      expect(rsidRDefaultRuns).toHaveLength(3);
    });
  });
});

describe('docx-comments write — F4: commentsIds.xml/commentsExtensible.xml stay consistent when present, never created when absent', () => {
  it('add appends a matching w16cid/w16cex entry (shared durable id) when both parts already exist', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/word365-realistic.docx',
        selector: textSelector('look strong across every region'),
        text: 'Which regions specifically?',
        author: 'user',
      });
      expect(result.ok).toBe(true);
      if (!result.ok) return;
      const newRawId = result.id.slice('w-'.length);

      const zip = await JSZip.loadAsync(await readFile(target));
      const commentsXml = await zip.file('word/comments.xml')!.async('string');
      const newCommentBlock = findCommentBlock(commentsXml, newRawId);
      expect(newCommentBlock).not.toBeNull();
      const newParaId = attr(newCommentBlock!, 'w14:paraId');
      expect(newParaId).not.toBeNull();

      const commentsIdsXml = await zip.file('word/commentsIds.xml')!.async('string');
      const commentsExtensibleXml = await zip.file('word/commentsExtensible.xml')!.async('string');

      const idsTags = selfClosingTags(commentsIdsXml, 'w16cid:commentId');
      expect(idsTags).toHaveLength(2); // the fixture's original entry + this new one
      // The ORIGINAL entry is untouched.
      expect(idsTags.some((t) => attr(t, 'w16cid:paraId') === 'AAAA0001' && attr(t, 'w16cid:durableId') === '00000001')).toBe(
        true
      );
      const newIdsTag = idsTags.find((t) => attr(t, 'w16cid:paraId') === newParaId);
      expect(newIdsTag).toBeDefined();
      const newDurableId = attr(newIdsTag!, 'w16cid:durableId');
      expect(newDurableId).not.toBeNull();
      expect(newDurableId).not.toBe('00000001'); // freshly minted, not reused

      const extTags = selfClosingTags(commentsExtensibleXml, 'w16cex:commentExtensible');
      expect(extTags).toHaveLength(2);
      expect(extTags.some((t) => attr(t, 'w16cex:durableId') === '00000001')).toBe(true); // original untouched
      const newExtTag = extTags.find((t) => attr(t, 'w16cex:durableId') === newDurableId);
      expect(newExtTag).toBeDefined(); // the SAME durable id links both new entries
      expect(attr(newExtTag!, 'w16cex:dateUtc')).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    });
  });

  it('a reply also gets a matching w16cid/w16cex entry — a reply is its own new <w:comment>', async () => {
    await withScratchCopy('word365-realistic.docx', async (target) => {
      const result = await replyToDocxComment({
        absolutePath: target,
        path: 'docs/word365-realistic.docx',
        id: 'w-0',
        text: 'Broken out by region in the appendix.',
        author: 'user',
      });
      expect(result.ok).toBe(true);

      const zip = await JSZip.loadAsync(await readFile(target));
      const idsTags = selfClosingTags(await zip.file('word/commentsIds.xml')!.async('string'), 'w16cid:commentId');
      const extTags = selfClosingTags(await zip.file('word/commentsExtensible.xml')!.async('string'), 'w16cex:commentExtensible');
      expect(idsTags).toHaveLength(2);
      expect(extTags).toHaveLength(2);
    });
  });

  it('never creates commentsIds.xml/commentsExtensible.xml for a file that never had them', async () => {
    await withScratchCopy('launch-brief.docx', async (target) => {
      const result = await addDocxComment({
        absolutePath: target,
        path: 'docs/launch-brief.docx',
        selector: textSelector('Keep support tickets about the update below 200 per week.'),
        text: 'By channel too, please.',
        author: 'user',
      });
      expect(result.ok).toBe(true);

      const zip = await JSZip.loadAsync(await readFile(target));
      expect(zip.file('word/commentsIds.xml')).toBeNull();
      expect(zip.file('word/commentsExtensible.xml')).toBeNull();
    });
  });
});
