// Pins T12 of the doc-comments build (docs/active/specs/2026-09-26-doc-
// comments-build-design.md §4.1-§4.3, §8): reading Excel legacy cell Notes
// off a REAL .xlsx, in the Electron main process.
//
// Fixture: tests/fixtures/doc-comments/q3-sales-by-rep.xlsx, generated by
// tests/fixtures/doc-comments/make-xlsx-fixture.mjs (see that file's header
// for exactly how and why, including the exceljs value-less-cell limitation
// that shaped the fixture's own cell choices) — a real workbook exceljs
// itself wrote, with three real Notes across two sheets.
import { describe, it, expect } from 'vitest';
import { readFile } from 'fs/promises';
import { join } from 'path';
import { readXlsxComments } from '../src/main/doc-comments/xlsx-comments';

const FIXTURE = join(__dirname, 'fixtures', 'doc-comments', 'q3-sales-by-rep.xlsx');

async function loadFixture(): Promise<Buffer> {
  return readFile(FIXTURE);
}

describe('xlsx-comments — parsing a workbook with a .note set', () => {
  it('reads the plain note on the FIRST sheet', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const q3Note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B2');
    expect(q3Note).toBeDefined();
    expect(q3Note?.author).toBe('person:Priya Shah');
    expect(q3Note?.text).toContain('West is Priya');
    expect(q3Note?.resolved).toBe(false);
    expect(q3Note?.replies).toEqual([]);
    expect(q3Note?.path).toBe('reports/q3-sales-by-rep.xlsx');
  });
});

describe('xlsx-comments — multi-sheet cell targeting', () => {
  it('finds a note on a NON-FIRST sheet, naming that sheet on the selector', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const byRepNote = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B4');
    expect(byRepNote).toBeDefined();
    if (byRepNote?.selector.kind !== 'cell') throw new Error('expected a cell selector');
    // A multi-tab workbook stamps the sheet name (§4.2: required only when
    // there's more than one tab) — never assumes sheet 0.
    expect(byRepNote.selector.selector.sheet).toBe('By rep');
    expect(byRepNote.text).toContain('North looks low for July');
  });

  it('does not mistake the first sheet for the whole workbook', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    // Three real notes total, spread across both sheets — a reader that only
    // looked at worksheet 0 would report just one.
    expect(result.comments).toHaveLength(3);
  });
});

describe('xlsx-comments — reply threads and the resolve marker', () => {
  it('splits a multi-turn note into the original comment plus its replies', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const threaded = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B5');
    expect(threaded).toBeDefined();
    expect(threaded?.author).toBe('person:Priya Shah');
    expect(threaded?.text).toContain('Diego’s numbers look great');
    expect(threaded?.replies).toHaveLength(1);
    expect(threaded?.replies[0]).toMatchObject({
      author: 'person:Marcus Lee',
      text: expect.stringContaining('Agreed'),
    });
  });

  it('reads the resolve marker as resolved: true, and strips it from the text', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const threaded = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B5');
    expect(threaded?.resolved).toBe(true);
    expect(threaded?.replies[0].text).not.toContain('yc:resolved');
    expect(threaded?.replies[0].text).not.toContain('​');
  });

  it('does NOT read resolve-like natural language as the resolve marker', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const q3Note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B2');
    // This note's text has nothing resolve-like in it, and in particular is
    // NOT flagged resolved just because a reader might loosely scan for the
    // word "resolved" anywhere in the body — only the exact machine token
    // triggers it (a plain string note like this one has none).
    expect(q3Note?.resolved).toBe(false);
  });
});

describe('xlsx-comments — not a valid workbook at all', () => {
  it('refuses honestly instead of throwing', async () => {
    const result = await readXlsxComments(Buffer.from('not a workbook'), 'reports/garbage.xlsx');
    expect(result).toEqual({ ok: false, error: 'invalid-xlsx' });
  });
});
