// Pins T12 of the doc-comments build (docs/active/specs/2026-09-26-doc-
// comments-build-design.md §4.1-§4.3, §8): reading Excel legacy cell Notes
// off a REAL .xlsx, in the Electron main process.
//
// Fixture: tests/fixtures/doc-comments/q3-sales-by-rep.xlsx, generated by
// tests/fixtures/doc-comments/make-xlsx-fixture.mjs (see that file's header
// for exactly how and why, including the exceljs value-less-cell limitation
// that shaped the fixture's own cell choices) — a real workbook exceljs
// itself wrote, with eight real Notes across two sheets.
import { describe, it, expect } from 'vitest';
import { readFile } from 'fs/promises';
import { join } from 'path';
import { readXlsxComments } from '../src/main/doc-comments/xlsx-comments';
import { buildDeclaredOversizeZip } from './fixtures/doc-comments/oversized-zip';

const FIXTURE = join(__dirname, 'fixtures', 'doc-comments', 'q3-sales-by-rep.xlsx');

async function loadFixture(): Promise<Buffer> {
  return readFile(FIXTURE);
}

describe('xlsx-comments — parsing a workbook with a .note set', () => {
  it('reads the plain note on the FIRST sheet', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const q3Note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B2');
    expect(q3Note).toBeDefined();
    expect(q3Note?.author).toBe('person:Priya Shah');
    expect(q3Note?.text).toContain('West is Priya');
    expect(q3Note?.resolved).toBe(false);
    expect(q3Note?.replies).toEqual([]);
    expect(q3Note?.path).toBe('reports/q3-sales-by-rep.xlsx');
  });
});

describe('xlsx-comments — multi-sheet cell targeting', () => {
  it('finds a note on a NON-FIRST sheet, naming that sheet on the selector', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const byRepNote = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B4');
    expect(byRepNote).toBeDefined();
    if (byRepNote?.selector.kind !== 'cell') throw new Error('expected a cell selector');
    // A multi-tab workbook stamps the sheet name (§4.2: required only when
    // there's more than one tab) — never assumes sheet 0.
    expect(byRepNote.selector.selector.sheet).toBe('By rep');
    expect(byRepNote.text).toContain('North looks low for July');
  });

  it('does not mistake the first sheet for the whole workbook', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    // Eight real notes total, spread across both sheets (B2/B18/B19/B20 on
    // Q3, B4/B5/B6/B7 on By rep) — a reader that only looked at worksheet 0
    // would report far fewer.
    expect(result.comments).toHaveLength(8);
  });
});

describe('xlsx-comments — reply threads and the resolve marker', () => {
  it('splits a multi-turn note into the original comment plus its replies', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;

    const threaded = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B5');
    expect(threaded).toBeDefined();
    expect(threaded?.author).toBe('person:Priya Shah');
    expect(threaded?.text).toContain('Diego’s numbers look great');
    expect(threaded?.replies).toHaveLength(1);
    expect(threaded?.replies[0]).toMatchObject({
      author: 'person:Marcus Lee',
      text: expect.stringContaining('Agreed'),
    });
  });

  it('reads the resolve marker as resolved: true, and strips it from the text', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const threaded = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B5');
    expect(threaded?.resolved).toBe(true);
    expect(threaded?.replies[0].text).not.toContain('yc:resolved');
    expect(threaded?.replies[0].text).not.toContain('​');
  });

  it('does NOT read resolve-like natural language as the resolve marker', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const q3Note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B2');
    // This note's text has nothing resolve-like in it, and in particular is
    // NOT flagged resolved just because a reader might loosely scan for the
    // word "resolved" anywhere in the body — only the exact machine token
    // triggers it (a plain string note like this one has none).
    expect(q3Note?.resolved).toBe(false);
  });
});

describe('xlsx-comments — not a valid workbook at all', () => {
  it('refuses honestly instead of throwing', async () => {
    const result = await readXlsxComments(Buffer.from('not a workbook'), 'reports/garbage.xlsx');
    expect(result).toEqual({ ok: false, error: 'invalid-xlsx' });
  });
});

// Implementation-review F1 (major): a bordered, VALUE-LESS cell still has a
// real note, but exceljs's `eachRow`/`eachCell` SKIP a value-less cell
// unless `includeEmpty: true` is passed — the pre-fix reader silently missed
// exactly this shape.
describe('xlsx-comments — a bordered, value-less cell', () => {
  it('finds its note (includeEmpty: true)', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B18');
    expect(note).toBeDefined();
    expect(note?.author).toBe('person:Priya Shah');
    expect(note?.text).toContain('Reserved for the September actuals');
    expect(note?.resolved).toBe(false);
  });
});

// Implementation-review F5 (major): a foreign note this app never wrote must
// never lose its text, and must never be misattributed to whatever precedes
// a colon that isn't shaped like this app's own "Name:" convention.
describe('xlsx-comments — foreign notes this app did not write', () => {
  it('keeps the full text of a colon-free note, with a neutral author', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B19');
    expect(note).toBeDefined();
    expect(note?.author).toBe('person:Unknown');
    expect(note?.text).toBe('Diego mentioned this figure needs a second look before the board meeting.');
  });

  it('does not misread a colon that is not this app’s own "Name:" convention', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B20');
    expect(note).toBeDefined();
    // "Check this number" is not a name this app would have written (lowercase
    // words follow the first) — the WHOLE line stays the comment's text.
    expect(note?.author).toBe('person:Unknown');
    expect(note?.text).toBe('Check this number: 42 seems low for August.');
  });
});

// Implementation-review F4: the resolve marker changed shape (a readable
// "✓ Resolved" line instead of a bracketed machine token), but the reader
// must keep recognizing the OLD token too, and must never mistake a real
// reply that happens to end with the same visible words — but no leading
// zero-width space — for the marker.
describe('xlsx-comments — the resolve marker, old and new', () => {
  it('reads the legacy bracketed-token marker as resolved (backward compatibility)', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B6');
    expect(note).toBeDefined();
    expect(note?.resolved).toBe(true);
    expect(note?.replies[0].text).not.toContain('yc:resolved');
  });

  it('does NOT read a real reply ending in plain "✓ Resolved" (no ZWSP) as resolved', async () => {
    const bytes = await loadFixture();
    const result = await readXlsxComments(bytes, 'reports/q3-sales-by-rep.xlsx');
    expect(result.ok).toBe(true);
    if (!result.ok) return;
    const note = result.comments.find((c) => c.selector.kind === 'cell' && c.selector.selector.cell === 'B7');
    expect(note).toBeDefined();
    expect(note?.resolved).toBe(false);
    expect(note?.text).toBe('Following up next week. ✓ Resolved');
  });
});

// Implementation-review F2 (major): a decompression-bomb-shaped archive must
// be refused BEFORE exceljs ever gets to unzip it. `buildDeclaredOversizeZip`
// builds a real, tiny zip whose central-directory metadata falsely declares
// a huge uncompressed size for one entry — the actual compressed bytes stay
// a few dozen bytes, so this test never allocates anywhere near the declared
// size itself; it only proves the pre-scan trips on the declared metadata.
describe('xlsx-comments — a decompression-bomb-shaped archive', () => {
  it('refuses before handing the bytes to exceljs', async () => {
    const bytes = await buildDeclaredOversizeZip(
      { 'xl/workbook.xml': '<workbook/>', 'xl/worksheets/sheet1.xml': '<worksheet/>' },
      'xl/worksheets/sheet1.xml',
      500 * 1024 * 1024
    );
    const result = await readXlsxComments(bytes, 'reports/bomb.xlsx');
    expect(result).toEqual({ ok: false, error: 'archive-too-large' });
  });
});
