// Pins T16 of the doc-comments build (docs/active/specs/2026-09-26-doc-
// comments-build-design.md §3.2a, §8): reading Word comments off a REAL
// .docx's comments.xml/commentsExtended.xml parts, in Kotlin, with
// java.util.zip + javax.xml.parsers — no Android framework classes, no
// instrumented/on-device test (a plain `./gradlew test` JVM unit test, per
// T16's own pinning-test row).
//
// Fixtures: app/src/test/resources/doc-comments/{launch-brief,no-comments,
// spanning-comment,deeply-nested,word365-realistic}.docx — the SAME files
// desktop/tests/docx-comments.test.ts reads (copied verbatim from
// desktop/tests/fixtures/doc-comments/), so a fixture drift here can never
// silently make the cross-platform parity claim compare two different
// inputs (the exact risk T16's own design row warns about).
//
// Golden parity: app/src/test/resources/doc-comments/golden/*.json is the
// REAL desktop `readDocxComments` reader's own output for each fixture,
// generated by desktop/tests/fixtures/doc-comments/generate-docx-golden.mjs
// (committed alongside this test — see that script's header for why it runs
// the actual TS reader rather than hand-transcribing expected JSON). Every
// golden-parity test below re-parses the golden JSON and asserts this
// module's own `PersistedComment.toJson()` output is structurally IDENTICAL,
// field for field.
package com.youcoded.app.doccomments

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Test
import java.io.File
import java.nio.file.Files
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

private fun fixtureFile(name: String): File {
    val resourceStream = object {}.javaClass.getResourceAsStream("/doc-comments/$name")
        ?: fail("missing test resource doc-comments/$name")
    val tmp = Files.createTempFile("ycd-docx-read-", "-$name").toFile()
    tmp.deleteOnExit()
    resourceStream.use { input -> tmp.outputStream().use { output -> input.copyTo(output) } }
    return tmp
}

private fun goldenComments(name: String): JSONArray {
    val stream = object {}.javaClass.getResourceAsStream("/doc-comments/golden/$name")
        ?: fail("missing golden fixture doc-comments/golden/$name")
    val json = stream.use { it.readBytes().toString(Charsets.UTF_8) }
    return JSONObject(json).getJSONArray("comments")
}

/** Deep-equality between two JSON trees (`org.json` gives no `equals()` that
 *  compares by value — `JSONObject.equals` is reference identity). Object
 *  keys are compared as sets before recursing (so a golden file with an
 *  extra/missing field fails loudly rather than passing on a subset match),
 *  arrays are compared in order (field order is never significant, item
 *  order always is — matches how every list in `PersistedComment` — replies,
 *  history, comments — is itself order-significant). */
// `JSONObject.keySet()` was only added to upstream org.json well after
// Android bundled its own fork into `android.jar` (which never got it) — the
// unit-test compile classpath resolves `org.json.JSONObject` against
// whichever jar Gradle orders first, which turned out to be `android.jar`'s
// older API surface (confirmed by an `Unresolved reference 'keySet'` compile
// failure while building this test). `.keys()` (an `Iterator<String>`) is
// the one key-enumeration method present on BOTH android.jar's org.json and
// the real `org.json:json` test dependency, so this helper uses that instead.
private fun keysOf(o: JSONObject): Set<String> {
    val out = mutableSetOf<String>()
    val it = o.keys()
    while (it.hasNext()) out.add(it.next())
    return out
}

private fun assertJsonEquals(expected: Any?, actual: Any?, path: String) {
    when (expected) {
        is JSONObject -> {
            assertTrue(actual is JSONObject, "$path: expected an object, got $actual")
            actual as JSONObject
            val expectedKeys = keysOf(expected)
            assertEquals(expectedKeys, keysOf(actual), "$path: key set differs")
            for (key in expectedKeys) {
                assertJsonEquals(expected.get(key), actual.get(key), "$path.$key")
            }
        }
        is JSONArray -> {
            assertTrue(actual is JSONArray, "$path: expected an array, got $actual")
            actual as JSONArray
            assertEquals(expected.length(), actual.length(), "$path: array length differs")
            for (i in 0 until expected.length()) {
                assertJsonEquals(expected.get(i), actual.get(i), "$path[$i]")
            }
        }
        else -> assertEquals(expected, actual, path)
    }
}

private fun assertMatchesGolden(fixtureBaseName: String, comments: List<PersistedComment>) {
    val expected = goldenComments("$fixtureBaseName.json")
    val actual = JSONArray(comments.map { it.toJson() })
    assertJsonEquals(expected, actual, fixtureBaseName)
}

class DocxCommentsTest {

    // ── Golden parity against the REAL desktop reader's own output ─────────

    @Test
    fun launchBriefMatchesTheDesktopReaderFieldForField() {
        val result = readDocxComments(fixtureFile("launch-brief.docx"), "docs/launch-brief.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("launch-brief", (result as DocxReadResult.Ok).comments)
    }

    @Test
    fun noCommentsMatchesTheDesktopReaderFieldForField() {
        val result = readDocxComments(fixtureFile("no-comments.docx"), "docs/no-comments.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("no-comments", (result as DocxReadResult.Ok).comments)
    }

    @Test
    fun spanningCommentMatchesTheDesktopReaderFieldForField() {
        val result = readDocxComments(fixtureFile("spanning-comment.docx"), "docs/spanning-comment.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("spanning-comment", (result as DocxReadResult.Ok).comments)
    }

    @Test
    fun deeplyNestedMatchesTheDesktopReaderFieldForField() {
        val result = readDocxComments(fixtureFile("deeply-nested.docx"), "docs/deeply-nested.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("deeply-nested", (result as DocxReadResult.Ok).comments)
    }

    @Test
    fun word365RealisticMatchesTheDesktopReaderFieldForField() {
        val result = readDocxComments(fixtureFile("word365-realistic.docx"), "docs/word365-realistic.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("word365-realistic", (result as DocxReadResult.Ok).comments)
    }

    // ── Behavioural pins mirroring desktop/tests/docx-comments.test.ts ─────

    @Test
    fun readsBothTopLevelCommentsWithTheirAuthorsTextAndResolvedState() {
        val result = readDocxComments(fixtureFile("launch-brief.docx"), "docs/launch-brief.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        val comments = (result as DocxReadResult.Ok).comments
        assertEquals(2, comments.size)

        val goalComment = comments.find { it.text.startsWith("Is 30% realistic") }
        assertTrue(goalComment != null, "expected a comment starting with 'Is 30% realistic'")
        assertEquals("person:Priya Shah", goalComment!!.author)
        assertTrue(goalComment.resolved, "w15:done=\"1\" should read as resolved")
        assertTrue(goalComment.replies.isEmpty())
        assertEquals("docs/launch-brief.docx", goalComment.path)
        val selector = goalComment.selector
        assertTrue(selector is CommentSelector.Text, "expected a text selector")
        assertEquals(
            "Move 30% of weekly active users to the new app within six weeks of launch.",
            (selector as CommentSelector.Text).selector.exact,
        )
    }

    @Test
    fun reconstructsAReplyThreadViaParaIdParent() {
        val result = readDocxComments(fixtureFile("launch-brief.docx"), "docs/launch-brief.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        val comments = (result as DocxReadResult.Ok).comments

        val timelineComment = comments.find { it.text.startsWith("Legal needs the beta terms") }
        assertTrue(timelineComment != null)
        assertTrue(!timelineComment!!.resolved, "w15:done=\"0\" should read as not resolved")
        assertEquals(1, timelineComment.replies.size)
        val reply = timelineComment.replies[0]
        assertEquals("person:Marcus Lee", reply.author)
        assertEquals("Confirmed with legal — the beta terms are ready as of this morning.", reply.text)
        // Account-ready id shape (§1.2): `${commentId}-r${n}`.
        assertEquals("${timelineComment.id}-r1", reply.id)
        // The reply itself is never a separate top-level record.
        assertTrue(comments.none { it.text.contains("Confirmed with legal") })
    }

    @Test
    fun buildsATextQuoteSelectorWithPrefixSuffixContext() {
        val result = readDocxComments(fixtureFile("launch-brief.docx"), "docs/launch-brief.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        val comments = (result as DocxReadResult.Ok).comments
        val c = comments.find { it.text.startsWith("Legal needs") }
        assertTrue(c != null)
        val selector = c!!.selector
        assertTrue(selector is CommentSelector.Text, "expected a text selector")
        val text = (selector as CommentSelector.Text).selector
        assertEquals("Beta opens to 500 customers on March 10", text.exact)
        assertTrue(text.prefix.isNotEmpty())
        assertTrue(text.suffix.contains(", with the public launch"))
    }

    @Test
    fun aDocxWithNoCommentsXmlPartReturnsAnEmptyListNeverACrash() {
        val result = readDocxComments(fixtureFile("no-comments.docx"), "docs/no-comments.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        assertEquals(emptyList(), (result as DocxReadResult.Ok).comments)
    }

    @Test
    fun notAValidZipRefusesHonestlyInsteadOfThrowing() {
        val garbage = Files.createTempFile("ycd-docx-read-", "-garbage.docx").toFile()
        garbage.deleteOnExit()
        garbage.writeBytes("not a docx".toByteArray(Charsets.UTF_8))
        val result = readDocxComments(garbage, "docs/garbage.docx")
        assertEquals(DocxReadResult.Err(DocxReadError.INVALID_DOCX), result)
    }

    @Test
    fun refusesWordCommentsXmlDeclaringAnImplausibleUncompressedSize() {
        val bytes = buildDeclaredOversizeZip(
            mapOf(
                "word/document.xml" to "<w:document><w:body/></w:document>",
                "word/comments.xml" to "<w:comments/>",
            ),
            "word/comments.xml",
            500L * 1024 * 1024,
        )
        val f = Files.createTempFile("ycd-docx-read-", "-bomb.docx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readDocxComments(f, "docs/bomb.docx")
        assertEquals(DocxReadResult.Err(DocxReadError.ARCHIVE_TOO_LARGE), result)
    }

    @Test
    fun refusesWordDocumentXmlDeclaringAnImplausibleUncompressedSize() {
        val bytes = buildDeclaredOversizeZip(
            mapOf(
                "word/document.xml" to "<w:document><w:body/></w:document>",
                "word/comments.xml" to "<w:comments/>",
            ),
            "word/document.xml",
            500L * 1024 * 1024,
        )
        val f = Files.createTempFile("ycd-docx-read-", "-bomb.docx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readDocxComments(f, "docs/bomb.docx")
        assertEquals(DocxReadResult.Err(DocxReadError.ARCHIVE_TOO_LARGE), result)
    }

    // F1 (implementation review — high, security): a part carrying an
    // internal-entity "billion laughs" DTD bomb must be refused, not parsed —
    // see `rejectDoctype`'s own doc comment (DocxComments.kt) for why this
    // pre-check exists ON TOP OF the factory's own `disallow-doctype-decl`
    // feature: this JVM test's own Xerces-backed parser WOULD also refuse the
    // DOCTYPE on its own (confirming this exact scenario can never surface a
    // real bug from `./gradlew test` alone), but Android's actual on-device
    // Expat-backed parser may silently ignore that feature name entirely,
    // which is exactly what this platform-independent substring check exists
    // to catch regardless of which parser implementation is on the classpath.
    @Test
    fun refusesADocxWhoseDocumentXmlCarriesAnInternalDtdEntityBomb() {
        val doctypeBomb = """
            <?xml version="1.0"?>
            <!DOCTYPE lolz [
             <!ENTITY lol "lol">
             <!ENTITY lol2 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
             <!ENTITY lol3 "&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;&lol2;">
            ]>
            <w:document><w:body><w:p><w:r><w:t>&lol3;</w:t></w:r></w:p></w:body></w:document>
        """.trimIndent()
        val bytes = buildPlainZip(
            mapOf(
                "word/document.xml" to doctypeBomb,
                "word/comments.xml" to "<w:comments/>",
            ),
        )
        val f = Files.createTempFile("ycd-docx-read-", "-doctype-bomb.docx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readDocxComments(f, "docs/doctype-bomb.docx")
        assertEquals(DocxReadResult.Err(DocxReadError.UNSAFE_XML), result)
    }

    @Test
    fun refusesACommentsXmlCarryingAnInternalDtdEntityBomb() {
        val doctypeBomb = """
            <?xml version="1.0"?>
            <!DOCTYPE lolz [<!ENTITY lol "lol"><!ENTITY lol2 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">]>
            <w:comments><w:comment w:id="1" w:author="X" w:date="2020-01-01T00:00:00Z"><w:p w14:paraId="AAAAAAAA"><w:r><w:t>&lol2;</w:t></w:r></w:p></w:comment></w:comments>
        """.trimIndent()
        val bytes = buildPlainZip(
            mapOf(
                "word/document.xml" to "<w:document><w:body/></w:document>",
                "word/comments.xml" to doctypeBomb,
            ),
        )
        val f = Files.createTempFile("ycd-docx-read-", "-doctype-bomb2.docx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readDocxComments(f, "docs/doctype-bomb2.docx")
        assertEquals(DocxReadResult.Err(DocxReadError.UNSAFE_XML), result)
    }

    // F3 (implementation review): the declared-size precheck
    // (`checkNamedEntriesWithinCeiling`) only ever reads CENTRAL DIRECTORY
    // metadata — a crafted entry can simply lie about it. This builds a REAL
    // zip bomb (word/comments.xml genuinely decompresses to well over the
    // 200MB ceiling) whose declared size is patched down to a few bytes, so
    // the declared-size precheck alone would wave it through; only the
    // byte-counting `readEntryBounded` backstop can catch this shape.
    @Test
    fun refusesACommentsXmlEntryWhoseRealDecompressedBytesExceedTheCeilingEvenWhenItsDeclaredSizeIsTiny() {
        val bytes = buildRealZipBomb(
            files = mapOf("word/document.xml" to "<w:document><w:body/></w:document>"),
            bombEntryName = "word/comments.xml",
            realUncompressedBytes = 201L * 1024 * 1024,
            declaredUncompressedSize = 10L,
        )
        val f = Files.createTempFile("ycd-docx-read-", "-real-bomb.docx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readDocxComments(f, "docs/real-bomb.docx")
        assertEquals(DocxReadResult.Err(DocxReadError.ARCHIVE_TOO_LARGE), result)
    }

    @Test
    fun findsACommentNestedThousandsOfLevelsDeepWithoutOverflowingTheCallStack() {
        val result = readDocxComments(fixtureFile("deeply-nested.docx"), "docs/deeply-nested.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        val comments = (result as DocxReadResult.Ok).comments
        assertEquals(1, comments.size)
        assertEquals("A comment buried very deep in the document tree.", comments[0].text)
        val selector = comments[0].selector
        assertTrue(selector is CommentSelector.Text)
        assertEquals(
            "A comment buried very deep in the document tree.",
            (selector as CommentSelector.Text).selector.exact,
        )
    }

    @Test
    fun capturesTheExactQuoteAcrossAParagraphBreakWithCorrectPrefixSuffix() {
        val result = readDocxComments(fixtureFile("spanning-comment.docx"), "docs/spanning-comment.docx")
        assertTrue(result is DocxReadResult.Ok, "expected Ok, got $result")
        val comments = (result as DocxReadResult.Ok).comments
        assertEquals(1, comments.size)
        val c = comments[0]
        assertEquals("Should this be one paragraph instead of two?", c.text)
        val selector = c.selector
        assertTrue(selector is CommentSelector.Text)
        val text = (selector as CommentSelector.Text).selector
        // The exact quote spans the paragraph break: text from two runs in
        // paragraph 1, the paragraph-break newline, then text from two more
        // runs in paragraph 2.
        assertEquals("first half \nsecond half.", text.exact)
        assertTrue(text.prefix.contains("Before the change:"))
        assertTrue(text.suffix.contains("After the note."))
    }

    @Test
    fun runsInAPlainJvmEnvironmentNoAndroidFrameworkClassInvolved() {
        // This is the whole point of T16's own pinning-test row ("a JVM unit
        // test, not an instrumented/on-device test, proving this runs in
        // plain ./gradlew test"): if this test class needed a real Android
        // Context, Robolectric, or android.* framework classes beyond the
        // stub jar's compile-time surface, it would fail to load or run
        // under a plain `./gradlew test` invocation. Reaching this
        // assertion at all is the pin.
        val result = readDocxComments(fixtureFile("no-comments.docx"), "docs/no-comments.docx")
        assertTrue(result is DocxReadResult.Ok)
    }
}
