// Cross-platform WRITE parity for T17 of the doc-comments build (docs/
// active/specs/2026-09-26-doc-comments-build-design.md §3.3/§3.2a, §8 T17,
// and the slice of T21's own "golden-fixture parity" guard this task's own
// brief asks be covered for docx specifically). Proves the Kotlin writer and
// the REAL desktop writer (`desktop/src/main/doc-comments/docx-comments.ts`)
// agree on the SAME operation against the SAME input fixture, not just that
// each independently passes its own tests.
//
// Fixtures: app/src/test/resources/doc-comments/write-golden/*.docx — the
// desktop writer's OWN real output, generated by the committed script
// `desktop/tests/fixtures/doc-comments/generate-docx-write-golden.mjs`
// (copied verbatim into this module's test resources, mirroring T16's own
// golden/*.json convention) — never hand-transcribed. Each `.docx` has a
// matching `.json` sidecar recording the EXACT operation/arguments used, so
// this test replays the identical operation with the Kotlin writer against a
// fresh copy of the SAME original source fixture.
//
// WHY the comparison excludes `createdAt` (and nothing else) — see the
// generator script's own "WHY NOT literal id/date injection" header comment:
// `w15:paraId`/durable ids are internal, never exposed in `PersistedComment`;
// `w:id` itself (add/reply's new comment id) IS fully deterministic —
// `(max existing w:id) + 1`, scanned fresh from the SAME original fixture by
// both writers — so it's compared for real equality, not excluded. Only the
// real wall-clock creation timestamp is excluded, the same way any two-
// process timing test excludes a real clock rather than trying to freeze it
// through a fragile cross-language mechanism.
package com.youcoded.app.doccomments

import org.json.JSONObject
import org.junit.Test
import java.io.File
import java.nio.file.Files
import java.util.zip.ZipFile
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

private fun resourceBytes(path: String): ByteArray {
    val stream = object {}.javaClass.getResourceAsStream("/doc-comments/$path") ?: fail("missing test resource doc-comments/$path")
    return stream.use { it.readBytes() }
}

private fun scratchCopyOf(bytes: ByteArray, name: String): File {
    val dir = Files.createTempDirectory("ycd-docx-parity-").toFile()
    dir.deleteOnExit()
    val target = File(dir, name)
    target.writeBytes(bytes)
    return target
}

private fun scratchHome(): File {
    val dir = Files.createTempDirectory("ycd-docx-parity-home-").toFile()
    dir.deleteOnExit()
    return dir
}

private fun textSelector(exact: String): CommentSelector.Text =
    CommentSelector.Text(TextQuoteSelector(exact = exact, prefix = "", suffix = "", occurrence = 0))

/** Every part name this feature's write path ever touches — everything else
 *  in the archive must come out byte-identical to the ORIGINAL fixture on
 *  both platforms, proven directly below rather than assumed. */
private val TOUCHED_PART_NAMES = setOf(
    "word/document.xml",
    "word/comments.xml",
    "word/commentsExtended.xml",
    "[Content_Types].xml",
    "word/_rels/document.xml.rels",
    "word/commentsIds.xml",
    "word/commentsExtensible.xml",
)

private fun entryBytes(file: File, name: String): ByteArray? {
    ZipFile(file).use { zip ->
        val entry = zip.getEntry(name) ?: return null
        return zip.getInputStream(entry).use { it.readBytes() }
    }
}

private fun entryNames(file: File): Set<String> {
    ZipFile(file).use { zip -> return zip.entries().asSequence().filter { !it.isDirectory }.map { it.name }.toSet() }
}

/** Field-for-field equality EXCEPT `createdAt` on the comment itself and on
 *  every reply — see this file's own header for why. */
private fun assertSameIgnoringTimestamps(expected: PersistedComment, actual: PersistedComment, label: String) {
    assertEquals(expected.id, actual.id, "$label: id")
    assertEquals(expected.path, actual.path, "$label: path")
    assertEquals(expected.selector, actual.selector, "$label: selector")
    assertEquals(expected.text, actual.text, "$label: text")
    assertEquals(expected.author, actual.author, "$label: author")
    assertEquals(expected.resolved, actual.resolved, "$label: resolved")
    assertEquals(expected.status, actual.status, "$label: status")
    assertEquals(expected.replies.size, actual.replies.size, "$label: replies.size")
    for (i in expected.replies.indices) {
        val e = expected.replies[i]
        val a = actual.replies[i]
        assertEquals(e.id, a.id, "$label: replies[$i].id")
        assertEquals(e.author, a.author, "$label: replies[$i].author")
        assertEquals(e.text, a.text, "$label: replies[$i].text")
    }
    assertEquals(expected.history.size, actual.history.size, "$label: history.size")
    for (i in expected.history.indices) {
        assertEquals(expected.history[i].by, actual.history[i].by, "$label: history[$i].by")
        assertEquals(expected.history[i].action, actual.history[i].action, "$label: history[$i].action")
    }
}

class DocxCommentsCrossPlatformParityTest {

    private fun runCase(caseName: String) {
        val json = JSONObject(String(resourceBytes("write-golden/$caseName.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val op = json.getString("op")
        val args = json.getJSONObject("args")
        val desktopResult = json.getJSONObject("result")

        val originalBytes = resourceBytes(fixture)
        val kotlinTarget = scratchCopyOf(originalBytes, fixture)
        val home = scratchHome()

        val actualIdOrUnit: Any = when (op) {
            "add" -> {
                val r = kotlinx.coroutines.runBlocking {
                    addDocxComment(kotlinTarget.absolutePath, path, textSelector(args.getString("exact")), args.getString("text"), args.getString("author"), home)
                }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin add failed: $r")
                (r as DocxWriteResult.Ok).value
            }
            "reply" -> {
                val r = kotlinx.coroutines.runBlocking {
                    replyToDocxComment(kotlinTarget.absolutePath, path, args.getString("id"), args.getString("text"), args.getString("author"), home)
                }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin reply failed: $r")
                Unit
            }
            "resolve" -> {
                val r = kotlinx.coroutines.runBlocking { resolveDocxComment(kotlinTarget.absolutePath, path, args.getString("id"), home) }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin resolve failed: $r")
                Unit
            }
            "reopen" -> {
                val r = kotlinx.coroutines.runBlocking { reopenDocxComment(kotlinTarget.absolutePath, path, args.getString("id"), home) }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin reopen failed: $r")
                Unit
            }
            "move" -> {
                val r = kotlinx.coroutines.runBlocking {
                    moveDocxComment(kotlinTarget.absolutePath, path, args.getString("id"), textSelector(args.getString("newExact")), home)
                }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin move failed: $r")
                Unit
            }
            // Edit/delete build (2026-09-28, design doc §"Edit and delete") —
            // this task's own T21 parity extension, previously "not extended
            // in this pass".
            "edit" -> {
                val r = kotlinx.coroutines.runBlocking { editDocxComment(kotlinTarget.absolutePath, path, args.getString("id"), args.getString("text"), home) }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin edit failed: $r")
                Unit
            }
            "edit-reply" -> {
                val r = kotlinx.coroutines.runBlocking {
                    editDocxReply(kotlinTarget.absolutePath, path, args.getString("id"), args.getString("replyId"), args.getString("text"), home)
                }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin edit-reply failed: $r")
                Unit
            }
            "delete" -> {
                val r = kotlinx.coroutines.runBlocking { deleteDocxComment(kotlinTarget.absolutePath, path, args.getString("id"), home) }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin delete failed: $r")
                Unit
            }
            "delete-reply" -> {
                val r = kotlinx.coroutines.runBlocking {
                    deleteDocxReply(kotlinTarget.absolutePath, path, args.getString("id"), args.getString("replyId"), home)
                }
                assertTrue(r is DocxWriteResult.Ok, "$caseName: Kotlin delete-reply failed: $r")
                Unit
            }
            else -> fail("unknown op $op")
        }

        // The new comment's own id (add) is fully deterministic — both
        // writers scan the SAME original fixture's own max existing w:id.
        if (op == "add") {
            assertEquals(desktopResult.getString("id"), actualIdOrUnit as String, "$caseName: new comment id must match desktop's")
        }

        // ── Structural parity, via THIS module's own reader on both sides ──
        val desktopGoldenFile = scratchCopyOf(resourceBytes("write-golden/$caseName.docx"), "$caseName-desktop.docx")
        val desktopRead = readDocxComments(desktopGoldenFile, path)
        val kotlinRead = readDocxComments(kotlinTarget, path)
        assertTrue(desktopRead is DocxReadResult.Ok, "$caseName: Kotlin reader failed on DESKTOP's own output: $desktopRead")
        assertTrue(kotlinRead is DocxReadResult.Ok, "$caseName: Kotlin reader failed on Kotlin's own output: $kotlinRead")
        val desktopComments = (desktopRead as DocxReadResult.Ok).comments.sortedBy { it.id }
        val kotlinComments = (kotlinRead as DocxReadResult.Ok).comments.sortedBy { it.id }
        assertEquals(desktopComments.size, kotlinComments.size, "$caseName: comment count differs")
        for (i in desktopComments.indices) {
            assertSameIgnoringTimestamps(desktopComments[i], kotlinComments[i], "$caseName comments[$i]")
        }

        // ── Every UNTOUCHED part is byte-identical: desktop's output ==
        // Kotlin's output == the ORIGINAL fixture, for every part name
        // neither writer's own algorithm is allowed to touch. ──
        val originalFile = scratchCopyOf(originalBytes, "orig-$caseName.docx")
        val namesToCheck = (entryNames(desktopGoldenFile) + entryNames(kotlinTarget)) - TOUCHED_PART_NAMES
        for (name in namesToCheck) {
            val original = entryBytes(originalFile, name)
            val desktopBytes = entryBytes(desktopGoldenFile, name)
            val kotlinBytes = entryBytes(kotlinTarget, name)
            assertTrue(desktopBytes != null && kotlinBytes != null, "$caseName: part $name missing from one output")
            assertTrue(desktopBytes!!.contentEquals(kotlinBytes), "$caseName: part $name differs between desktop and Kotlin output")
            if (original != null) {
                assertTrue(original.contentEquals(kotlinBytes), "$caseName: part $name was touched by the Kotlin writer but shouldn't have been")
            }
        }
    }

    @Test fun addLaunchBrief() = runCase("add-launch-brief")
    @Test fun addSpanningComment() = runCase("add-spanning-comment")
    @Test fun addWord365Realistic() = runCase("add-word365-realistic")
    @Test fun replyLaunchBrief() = runCase("reply-launch-brief")
    @Test fun resolveSpanningComment() = runCase("resolve-spanning-comment")
    @Test fun reopenLaunchBrief() = runCase("reopen-launch-brief")
    @Test fun moveLaunchBrief() = runCase("move-launch-brief")
    @Test fun moveWord365Realistic() = runCase("move-word365-realistic")

    // Edit/delete build (2026-09-28, design doc §"Edit and delete") — this
    // task's own T21 parity extension, previously "not extended in this
    // pass" per that section's own closing note. All four reuse launch-
    // brief.docx's real w-0 (no reply) and w-1 (one reply, w-1-r1).
    @Test fun editLaunchBrief() = runCase("edit-launch-brief")
    @Test fun editReplyLaunchBrief() = runCase("edit-reply-launch-brief")
    @Test fun deleteReplyLaunchBrief() = runCase("delete-reply-launch-brief")
    // Deletes w-1's WHOLE thread — root + its one reply — the direct proof
    // that a delete removes every reply chained to a root via
    // w15:paraIdParent, not just the root's own document.xml anchor.
    @Test fun deleteThreadLaunchBrief() = runCase("delete-thread-launch-brief")
}
