// Cross-platform WRITE parity for T21 of the doc-comments build (docs/
// active/specs/2026-09-26-doc-comments-build-design.md §4.3/§4.3a, §8 T21,
// §9.3). Xlsx sibling of `DocxCommentsCrossPlatformParityTest.kt` (see that
// file's own header for the shared rationale) — proves the Kotlin writer and
// the REAL desktop writer (`desktop/src/main/doc-comments/xlsx-comments.ts`)
// agree on the SAME operation(s) against the SAME real-file input, not just
// that each independently passes its own suite.
//
// Fixtures: app/src/test/resources/doc-comments/write-golden/{add-docling,
// move-docling,resolve-b19-sibling,elden-sequence}.{xlsx,json} — the
// desktop writer's OWN real output, generated by the committed script
// `desktop/tests/fixtures/doc-comments/generate-xlsx-write-golden.mjs`
// (copied verbatim into this module's test resources), never hand-
// transcribed.
//
// WHY this does NOT do a docx-style "every untouched PART is byte-identical"
// check: xlsx's own per-sheet threadedComment{N}.xml/comments{N}.xml/
// vmlDrawing{N}.vml numbering is dynamic (assigned by "next available N",
// per shared-fixtures/doc-comments/xlsx-threaded-reference/manifest.json's
// own `partPaths.numberingScheme` note) and a comment on a sheet that
// previously had NONE (this test's own `elden-sequence` case, deliberately
// targeting `Sorceries & Incantations List` — confirmed comment-free in that
// same manifest) creates brand-new parts whose exact names are an
// IMPLEMENTATION DETAIL neither writer's own contract fixes. The guarantee
// this design actually needs — "an unrelated existing thread is never
// disturbed" (§9.3, §4.2's own multi-thread-per-cell risk) — is instead
// proven MORE DIRECTLY and MORE STRONGLY here: reading back the WHOLE
// ~700-thread comment set from both Kotlin's own output and desktop's
// committed golden output and asserting every thread OTHER than the one this
// operation touches is byte-for-byte identical in its OWN read-back shape
// (id, text, author, resolved, replies, history) — a corrupted or dropped
// unrelated part would show up here regardless of which physical XML part it
// lived in.
//
// WHY the touched thread's own `id`/GUID is excluded from the cross-writer
// comparison: `mutateAddXlsxComment` mints a fresh random GUID per call
// (§4.2's `guidFormat`) — two INDEPENDENT writers applied to the same input
// never produce the same GUID for a BRAND-NEW thread, which is expected, not
// drift. A `resolve`/`move` against a PRE-EXISTING thread (`resolve-b19-
// sibling`, `move-docling`) keeps that thread's own real, content-derived
// GUID unchanged, so those two cases DO compare the id for exact equality.
//
// WHY `createdAt` is excluded universally (mirroring the docx parity test's
// own identical exclusion): a `reply`/`add` step stamps real wall-clock time
// (`xlsx-comments.ts`'s `formatThreadedDate(new Date())`) — two independent
// writer runs, run at two different real moments, can never agree on it.
package com.youcoded.app.doccomments

import org.json.JSONObject
import org.junit.Test
import java.io.File
import java.nio.file.Files
import java.util.zip.ZipFile
import kotlinx.coroutines.runBlocking
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

private fun xlsxParityResourceBytes(path: String): ByteArray {
    val stream = object {}.javaClass.getResourceAsStream("/doc-comments/$path") ?: fail("missing test resource doc-comments/$path")
    return stream.use { it.readBytes() }
}

private fun xlsxParityScratchCopy(bytes: ByteArray, name: String): File {
    val dir = Files.createTempDirectory("ycd-xlsx-parity-").toFile()
    dir.deleteOnExit()
    val target = File(dir, name)
    target.writeBytes(bytes)
    return target
}

private fun xlsxParityScratchHome(): File {
    val dir = Files.createTempDirectory("ycd-xlsx-parity-home-").toFile()
    dir.deleteOnExit()
    return dir
}

private fun xlsxParitySelector(cell: String, sheet: String?): CommentSelector = CommentSelector.Cell(CellSelector(cell, sheet))

/** File-private zip introspection for the delete-last-comment-fresh
 *  structural cleanup check — DocxCommentsCrossPlatformParityTest.kt's own
 *  `entryNames`/`entryBytes` are file-private in Kotlin, so this file needs
 *  its own copies rather than sharing them. */
private fun xlsxParityEntryNames(file: File): Set<String> {
    ZipFile(file).use { zip -> return zip.entries().asSequence().filter { !it.isDirectory }.map { it.name }.toSet() }
}

private fun xlsxParityEntryBytes(file: File, name: String): ByteArray? {
    ZipFile(file).use { zip ->
        val entry = zip.getEntry(name) ?: return null
        return zip.getInputStream(entry).use { it.readBytes() }
    }
}

private fun xlsxParityReadOk(file: File, path: String): List<PersistedComment> {
    val r = readXlsxComments(file, path)
    assertTrue(r is XlsxReadResult.Ok, "expected Ok reading $path, got $r")
    return (r as XlsxReadResult.Ok).comments
}

private fun xlsxParityFindByCell(comments: List<PersistedComment>, cell: String, sheet: String? = null): PersistedComment {
    val match = comments.filter { c ->
        val sel = c.selector
        sel is CommentSelector.Cell && sel.selector.cell == cell && (sheet == null || sel.selector.sheet == sheet)
    }
    assertEquals(1, match.size, "expected exactly one thread at $cell${if (sheet != null) "/$sheet" else ""}, found ${match.size}")
    return match[0]
}

/** Field-for-field equality EXCLUDING `id` and `createdAt` — see this file's
 *  own header for why both are expected to differ between two independent
 *  writer runs for a newly-minted or freshly-timestamped thread. */
private fun assertSameThreadContent(expected: PersistedComment, actual: PersistedComment, label: String) {
    assertEquals(expected.selector, actual.selector, "$label: selector")
    assertEquals(expected.text, actual.text, "$label: text")
    assertEquals(expected.author, actual.author, "$label: author")
    assertEquals(expected.resolved, actual.resolved, "$label: resolved")
    assertEquals(expected.replies.size, actual.replies.size, "$label: replies.size")
    for (i in expected.replies.indices) {
        assertEquals(expected.replies[i].author, actual.replies[i].author, "$label: replies[$i].author")
        assertEquals(expected.replies[i].text, actual.replies[i].text, "$label: replies[$i].text")
    }
    assertEquals(expected.history.size, actual.history.size, "$label: history.size")
    for (i in expected.history.indices) {
        assertEquals(expected.history[i].by, actual.history[i].by, "$label: history[$i].by")
        assertEquals(expected.history[i].action, actual.history[i].action, "$label: history[$i].action")
    }
}

/** Same as `assertSameThreadContent`, plus `id` — for a thread this
 *  operation never re-mints (a pre-existing, content-derived GUID). */
private fun assertSameThreadContentAndId(expected: PersistedComment, actual: PersistedComment, label: String) {
    assertEquals(expected.id, actual.id, "$label: id")
    assertSameThreadContent(expected, actual, label)
}

/** Proves every thread OTHER than `excludeIds` is byte-for-byte identical
 *  (including id, excluding createdAt) between Kotlin's own output and
 *  desktop's committed golden output — the direct "an unrelated thread is
 *  never disturbed" guarantee this file's own header explains. */
private fun assertUnrelatedThreadsUntouched(desktopComments: List<PersistedComment>, kotlinComments: List<PersistedComment>, excludeIds: Set<String>, label: String) {
    val desktopRest = desktopComments.filter { it.id !in excludeIds }.sortedBy { it.id }
    val kotlinRest = kotlinComments.filter { it.id !in excludeIds }.sortedBy { it.id }
    assertEquals(desktopRest.size, kotlinRest.size, "$label: unrelated-thread count differs")
    for (i in desktopRest.indices) {
        assertSameThreadContentAndId(desktopRest[i], kotlinRest[i], "$label unrelated[$i]")
    }
}

class XlsxCommentsCrossPlatformParityTest {

    // ── add-docling: a brand-new thread on the real Excel-authored file ────
    @Test
    fun addDocling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/add-docling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val result = runBlocking {
            addXlsxComment(kotlinTarget.absolutePath, path, xlsxParitySelector(args.getString("cell"), null), args.getString("text"), args.getString("author"), home)
        }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin add failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/add-docling.xlsx"), "desktop-add-docling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        val desktopNew = xlsxParityFindByCell(desktopComments, args.getString("cell"))
        val kotlinNew = xlsxParityFindByCell(kotlinComments, args.getString("cell"))
        assertSameThreadContent(desktopNew, kotlinNew, "addDocling new thread")
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(desktopNew.id, kotlinNew.id), "addDocling")
    }

    // ── move-docling: relocate the real, pre-existing F7 thread ────────────
    @Test
    fun moveDocling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/move-docling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val result = runBlocking {
            moveXlsxComment(kotlinTarget.absolutePath, path, args.getString("id"), xlsxParitySelector(args.getString("newCell"), null), home)
        }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin move failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/move-docling.xlsx"), "desktop-move-docling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        // F7's own GUID survives a move unchanged (§4.2/§4.3: "never mints
        // fresh GUIDs on a move") — locate the moved thread by its NEW cell
        // on both sides, then confirm both sides agree it's still the SAME
        // original GUID (the suffix after the cell component).
        val desktopMoved = xlsxParityFindByCell(desktopComments, args.getString("newCell"))
        val kotlinMoved = xlsxParityFindByCell(kotlinComments, args.getString("newCell"))
        assertSameThreadContent(desktopMoved, kotlinMoved, "moveDocling moved thread")
        // id shape is `xt-{sheetId}-{cell}-{GUID}`, and a GUID itself
        // contains dashes — split with a limit of 4 so element [3] is the
        // WHOLE GUID, not just the text after its own last dash.
        val originalGuid = args.getString("id").split("-", limit = 4)[3]
        assertTrue(desktopMoved.id.endsWith(originalGuid), "desktop's moved id should keep the original GUID unchanged (§4.2/§4.3: never mints fresh GUIDs on a move)")
        assertTrue(kotlinMoved.id.endsWith(originalGuid), "Kotlin's moved id should keep the original GUID unchanged")
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(desktopMoved.id, kotlinMoved.id), "moveDocling")
    }

    // ── resolve-b19-sibling: resolve ONE of elden's real 5 independent
    // threads on B19 — the other four (and every other thread in the whole
    // ~700-thread workbook) must be completely untouched. ──
    @Test
    fun resolveB19Sibling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/resolve-b19-sibling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")
        val targetId = args.getString("id")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val before = xlsxParityReadOk(kotlinTarget, path)
        val b19Before = before.filter { c -> val s = c.selector; s is CommentSelector.Cell && s.selector.cell == "B19" }
        assertEquals(5, b19Before.size, "elden's real B19 cell carries 5 independent threads")

        val result = runBlocking { resolveXlsxComment(kotlinTarget.absolutePath, path, targetId, home) }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin resolve failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/resolve-b19-sibling.xlsx"), "desktop-resolve-b19-sibling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        // Same pre-existing GUID both sides (never re-minted by resolve) —
        // exact id equality is meaningful here, unlike the `add`-originated
        // cases above.
        val desktopTarget = desktopComments.find { it.id == targetId } ?: fail("target $targetId missing from desktop golden")
        val kotlinTarget2 = kotlinComments.find { it.id == targetId } ?: fail("target $targetId missing from Kotlin output")
        assertSameThreadContentAndId(desktopTarget, kotlinTarget2, "resolveB19Sibling target")
        assertTrue(kotlinTarget2.resolved, "the resolved thread should read back resolved")

        // The other FOUR B19 threads (and the ~700 other threads workbook-
        // wide) are byte-for-byte untouched on BOTH sides.
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(targetId), "resolveB19Sibling")
        val b19After = kotlinComments.filter { c -> val s = c.selector; s is CommentSelector.Cell && s.selector.cell == "B19" }
        assertEquals(5, b19After.size, "resolving one B19 thread must not drop or merge its siblings")
    }

    // ── elden-sequence: add (fresh sheet, no prior comment parts) -> reply
    // -> resolve -> reopen -> move CROSS-SHEET (onto a sheet that already
    // has other threads) — the literal "add+reply+resolve+move sequence"
    // design review 1/3 (F11/F2) names, run end to end with the Kotlin
    // writer against the SAME real elden workbook desktop wrote it against. ──
    @Test
    fun eldenSequence() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/elden-sequence.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val steps = json.getJSONArray("steps")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        var currentId: String? = null
        for (i in 0 until steps.length()) {
            val step = steps.getJSONObject(i)
            val op = step.getString("op")
            val args = step.getJSONObject("args")
            when (op) {
                "add" -> {
                    val r = runBlocking {
                        addXlsxComment(kotlinTarget.absolutePath, path, xlsxParitySelector(args.getString("cell"), (if (args.has("sheet")) args.getString("sheet") else null)), args.getString("text"), args.getString("author"), home)
                    }
                    assertTrue(r is XlsxWriteResult.Ok, "eldenSequence step $i (add) failed: $r")
                    currentId = (r as XlsxWriteResult.Ok).value
                }
                "reply" -> {
                    val id = currentId ?: fail("eldenSequence step $i (reply) has no current thread id")
                    val r = runBlocking { replyToXlsxComment(kotlinTarget.absolutePath, path, id, args.getString("text"), args.getString("author"), home) }
                    assertTrue(r is XlsxWriteResult.Ok, "eldenSequence step $i (reply) failed: $r")
                }
                "resolve" -> {
                    val id = currentId ?: fail("eldenSequence step $i (resolve) has no current thread id")
                    val r = runBlocking { resolveXlsxComment(kotlinTarget.absolutePath, path, id, home) }
                    assertTrue(r is XlsxWriteResult.Ok, "eldenSequence step $i (resolve) failed: $r")
                }
                "reopen" -> {
                    val id = currentId ?: fail("eldenSequence step $i (reopen) has no current thread id")
                    val r = runBlocking { reopenXlsxComment(kotlinTarget.absolutePath, path, id, home) }
                    assertTrue(r is XlsxWriteResult.Ok, "eldenSequence step $i (reopen) failed: $r")
                }
                "move" -> {
                    val id = currentId ?: fail("eldenSequence step $i (move) has no current thread id")
                    val r = runBlocking {
                        moveXlsxComment(kotlinTarget.absolutePath, path, id, xlsxParitySelector(args.getString("newCell"), (if (args.has("newSheet")) args.getString("newSheet") else null)), home)
                    }
                    assertTrue(r is XlsxWriteResult.Ok, "eldenSequence step $i (move) failed: $r")
                    currentId = (r as XlsxWriteResult.Ok).value
                }
                else -> fail("eldenSequence: unknown op $op")
            }
        }

        val lastStep = steps.getJSONObject(steps.length() - 1)
        assertEquals("move", lastStep.getString("op"), "eldenSequence's own last step must be the move (this test's own final-state assertions assume it)")
        val moveArgs = lastStep.getJSONObject("args")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/elden-sequence.xlsx"), "desktop-elden-sequence.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        val desktopFinal = xlsxParityFindByCell(desktopComments, moveArgs.getString("newCell"), moveArgs.getString("newSheet"))
        val kotlinFinal = xlsxParityFindByCell(kotlinComments, moveArgs.getString("newCell"), moveArgs.getString("newSheet"))
        assertSameThreadContent(desktopFinal, kotlinFinal, "eldenSequence final thread")
        assertEquals(1, kotlinFinal.replies.size, "the reply survives resolve+reopen+move")
        // Sequence order is add -> reply -> resolve -> reopen -> move: reopen
        // is the LAST op that touches `resolved`, and move never changes it,
        // so the final state must be UNRESOLVED.
        assertTrue(!kotlinFinal.resolved, "resolve followed by reopen (then a move, which doesn't touch resolved) must leave the thread unresolved")
        assertTrue(!desktopFinal.resolved, "desktop's own golden output must show the same final unresolved state")

        // The source sheet (`Sorceries & Incantations List`) must have NO
        // thread left at the original cell — the move removed it, it did not
        // duplicate it.
        val stillAtSource = kotlinComments.any { c -> val s = c.selector; s is CommentSelector.Cell && s.selector.cell == "ZZ999" && s.selector.sheet == "Sorceries & Incantations List" }
        assertTrue(!stillAtSource, "the OLD cell must have no thread left after the move")

        // Every one of the ~700 OTHER real threads in this workbook —
        // including the other 4 threads sharing B19 — is untouched.
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(desktopFinal.id, kotlinFinal.id), "eldenSequence")
    }

    // ── Edit/delete build (2026-09-28, design doc §"Edit and delete") — this
    // task's own T21 parity extension, previously "not extended in this
    // pass" per that section's own closing note. Reuses docling's real F7
    // (root + one reply) and G12 (root only) — the same two threads xlsx-
    // comments.test.ts's own edit/delete suite already exercises. ──────────

    @Test
    fun editDocling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/edit-docling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")
        val targetId = args.getString("id")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val result = runBlocking { editXlsxComment(kotlinTarget.absolutePath, path, targetId, args.getString("text"), home) }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin edit failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/edit-docling.xlsx"), "desktop-edit-docling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        // G12's own pre-existing GUID is never re-minted by edit.
        val desktopEdited = desktopComments.find { it.id == targetId } ?: fail("target $targetId missing from desktop golden")
        val kotlinEdited = kotlinComments.find { it.id == targetId } ?: fail("target $targetId missing from Kotlin output")
        assertSameThreadContentAndId(desktopEdited, kotlinEdited, "editDocling target")
        assertEquals(args.getString("text"), kotlinEdited.text, "the edited text should read back")
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(targetId), "editDocling")
    }

    @Test
    fun editReplyDocling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/edit-reply-docling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")
        val targetId = args.getString("id")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val result = runBlocking { editXlsxReply(kotlinTarget.absolutePath, path, targetId, args.getString("replyId"), args.getString("text"), home) }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin edit-reply failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/edit-reply-docling.xlsx"), "desktop-edit-reply-docling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        val desktopTarget = desktopComments.find { it.id == targetId } ?: fail("target $targetId missing from desktop golden")
        val kotlinTarget2 = kotlinComments.find { it.id == targetId } ?: fail("target $targetId missing from Kotlin output")
        assertSameThreadContentAndId(desktopTarget, kotlinTarget2, "editReplyDocling target")
        assertEquals(1, kotlinTarget2.replies.size, "the root's single reply must survive an edit")
        assertEquals(args.getString("text"), kotlinTarget2.replies[0].text, "the edited reply text should read back")
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(targetId), "editReplyDocling")
    }

    @Test
    fun deleteReplyDocling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/delete-reply-docling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")
        val targetId = args.getString("id")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val result = runBlocking { deleteXlsxReply(kotlinTarget.absolutePath, path, targetId, args.getString("replyId"), home) }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin delete-reply failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/delete-reply-docling.xlsx"), "desktop-delete-reply-docling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        // The root survives, with the same pre-existing GUID (never re-minted
        // by a reply delete), but now with zero replies.
        val desktopTarget = desktopComments.find { it.id == targetId } ?: fail("target $targetId missing from desktop golden")
        val kotlinTarget2 = kotlinComments.find { it.id == targetId } ?: fail("target $targetId missing from Kotlin output")
        assertSameThreadContentAndId(desktopTarget, kotlinTarget2, "deleteReplyDocling target")
        assertEquals(0, kotlinTarget2.replies.size, "the reply must be gone, the root must survive")
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(targetId), "deleteReplyDocling")
    }

    @Test
    fun deleteThreadDocling() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/delete-thread-docling.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val step = json.getJSONArray("steps").getJSONObject(0)
        val args = step.getJSONObject("args")
        val targetId = args.getString("id")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val result = runBlocking { deleteXlsxComment(kotlinTarget.absolutePath, path, targetId, home) }
        assertTrue(result is XlsxWriteResult.Ok, "Kotlin delete failed: $result")

        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/delete-thread-docling.xlsx"), "desktop-delete-thread-docling.xlsx")
        val desktopComments = xlsxParityReadOk(desktopGolden, path)
        val kotlinComments = xlsxParityReadOk(kotlinTarget, path)

        assertTrue(desktopComments.none { it.id == targetId }, "deleted thread must be gone from desktop's golden")
        assertTrue(kotlinComments.none { it.id == targetId }, "deleted thread must be gone from Kotlin's output")
        // G12's own independent thread on the same sheet survives untouched
        // on BOTH sides.
        assertTrue(kotlinComments.any { c -> val s = c.selector; s is CommentSelector.Cell && s.selector.cell == "G12" }, "G12's independent thread must survive")
        assertUnrelatedThreadsUntouched(desktopComments, kotlinComments, setOf(targetId), "deleteThreadDocling")
    }

    // ── delete-last-comment-fresh: add the ONLY comment to a brand-new,
    // comment-free workbook, then delete it — proves Kotlin's own
    // `cleanupEmptyCommentPartsIfNeeded` removes every comment part/rel/
    // content-type override/`<legacyDrawing>` the same way desktop's does,
    // leaving the workbook exactly as if it never had comments. ────────────
    @Test
    fun deleteLastCommentFresh() {
        val json = JSONObject(String(xlsxParityResourceBytes("write-golden/delete-last-comment-fresh.json"), Charsets.UTF_8))
        val fixture = json.getString("fixture")
        val path = json.getString("path")
        val steps = json.getJSONArray("steps")
        val addArgs = steps.getJSONObject(0).getJSONObject("args")

        val originalBytes = xlsxParityResourceBytes(fixture)
        val kotlinTarget = xlsxParityScratchCopy(originalBytes, fixture)
        val home = xlsxParityScratchHome()

        val addResult = runBlocking {
            addXlsxComment(kotlinTarget.absolutePath, path, xlsxParitySelector(addArgs.getString("cell"), null), addArgs.getString("text"), addArgs.getString("author"), home)
        }
        assertTrue(addResult is XlsxWriteResult.Ok, "Kotlin add failed: $addResult")
        val newId = (addResult as XlsxWriteResult.Ok).value

        val deleteResult = runBlocking { deleteXlsxComment(kotlinTarget.absolutePath, path, newId, home) }
        assertTrue(deleteResult is XlsxWriteResult.Ok, "Kotlin delete failed: $deleteResult")

        val kotlinRead = readXlsxComments(kotlinTarget, path)
        assertTrue(kotlinRead is XlsxReadResult.Ok, "expected Ok, got $kotlinRead")
        assertEquals(0, (kotlinRead as XlsxReadResult.Ok).comments.size, "the workbook must read back with zero comments")

        // Same structural cleanup as desktop's own committed golden: every
        // comment part, its rels, content-type overrides and the worksheet's
        // own <legacyDrawing> are all gone.
        val entries = xlsxParityEntryNames(kotlinTarget)
        assertTrue("xl/comments1.xml" !in entries, "comments1.xml must be gone")
        assertTrue("xl/drawings/vmlDrawing1.vml" !in entries, "vmlDrawing1.vml must be gone")
        assertTrue("xl/threadedComments/threadedComment1.xml" !in entries, "threadedComment1.xml must be gone")
        val worksheetXml = String(xlsxParityEntryBytes(kotlinTarget, "xl/worksheets/sheet1.xml") ?: fail("sheet1.xml missing"), Charsets.UTF_8)
        assertTrue(!worksheetXml.contains("legacyDrawing"), "legacyDrawing must be gone")

        // The committed desktop golden itself must show the identical
        // zero-comments, parts-gone end state.
        val desktopGolden = xlsxParityScratchCopy(xlsxParityResourceBytes("write-golden/delete-last-comment-fresh.xlsx"), "desktop-delete-last-comment-fresh.xlsx")
        val desktopRead = readXlsxComments(desktopGolden, path)
        assertTrue(desktopRead is XlsxReadResult.Ok, "expected Ok, got $desktopRead")
        assertEquals(0, (desktopRead as XlsxReadResult.Ok).comments.size, "desktop's golden must also read back with zero comments")
        val desktopEntries = xlsxParityEntryNames(desktopGolden)
        assertTrue("xl/comments1.xml" !in desktopEntries, "desktop golden: comments1.xml must be gone")
        assertTrue("xl/threadedComments/threadedComment1.xml" !in desktopEntries, "desktop golden: threadedComment1.xml must be gone")
    }
}
