// Pins T18 of the doc-comments build (docs/active/specs/2026-09-26-doc-
// comments-build-design.md §4.3a, §8): reading Excel legacy cell Notes off a
// REAL .xlsx, in Kotlin, with java.util.zip + javax.xml.parsers — no Android
// framework classes, no instrumented/on-device test (a plain `./gradlew
// test` JVM unit test, per T18's own pinning-test row).
//
// Fixture: app/src/test/resources/doc-comments/q3-sales-by-rep.xlsx — the
// SAME file desktop/tests/xlsx-comments.test.ts (T12) reads, copied verbatim
// from desktop/tests/fixtures/doc-comments/, so a fixture drift here can
// never silently make the cross-platform parity claim compare two different
// inputs (the exact risk T18's own design row warns about — the same
// reasoning T16's own docx test documents for its fixtures).
//
// Golden parity: app/src/test/resources/doc-comments/golden/
// q3-sales-by-rep.json is the REAL desktop `readXlsxComments` reader's own
// output, generated by desktop/tests/fixtures/doc-comments/
// generate-xlsx-golden.mjs (committed alongside this test). **`createdAt` is
// EXCLUDED from the comparison, top-level and within every reply** — unlike
// docx's `w:date`-derived (deterministic) timestamp, a legacy Excel Note
// carries NO timestamp of its own (§4.1), so both readers stamp a fresh
// wall-clock value at READ time (`Date.now()` on desktop, `System.
// currentTimeMillis()` here) — comparing it byte-for-byte across two
// separate processes run at two different moments would be asserting on
// wall-clock time, exactly what `.claude/rules/test-suite-hygiene.md` (§
// "Never assert on wall-clock time") forbids. Every OTHER field is compared
// exactly, field for field.
package com.youcoded.app.doccomments

import org.json.JSONArray
import org.json.JSONObject
import org.junit.Test
import java.io.File
import java.nio.file.Files
import kotlin.test.assertEquals
import kotlin.test.assertTrue
import kotlin.test.fail

private fun fixtureFile(name: String): File {
    val resourceStream = object {}.javaClass.getResourceAsStream("/doc-comments/$name")
        ?: fail("missing test resource doc-comments/$name")
    val tmp = Files.createTempFile("ycd-xlsx-read-", "-$name").toFile()
    tmp.deleteOnExit()
    resourceStream.use { input -> tmp.outputStream().use { output -> input.copyTo(output) } }
    return tmp
}

private fun goldenComments(name: String): JSONArray {
    val stream = object {}.javaClass.getResourceAsStream("/doc-comments/golden/$name")
        ?: fail("missing golden fixture doc-comments/golden/$name")
    val json = stream.use { it.readBytes().toString(Charsets.UTF_8) }
    return JSONObject(json).getJSONArray("comments")
}

// Same `.keys()`-based enumeration as DocxCommentsTest.kt — see that file's
// own comment for why `.keySet()` isn't available on this compile classpath.
private fun keysOf(o: JSONObject): Set<String> {
    val out = mutableSetOf<String>()
    val it = o.keys()
    while (it.hasNext()) out.add(it.next())
    return out
}

/** Deep-equality between two JSON trees, identical to DocxCommentsTest.kt's
 *  own `assertJsonEquals` EXCEPT that any key named `createdAt` is skipped
 *  entirely (still required to be PRESENT and a number, never absent or the
 *  wrong type — just not compared for its specific value; see this file's
 *  own header for why). */
private fun assertJsonEqualsIgnoringCreatedAt(expected: Any?, actual: Any?, path: String) {
    when (expected) {
        is JSONObject -> {
            assertTrue(actual is JSONObject, "$path: expected an object, got $actual")
            actual as JSONObject
            val expectedKeys = keysOf(expected)
            assertEquals(expectedKeys, keysOf(actual), "$path: key set differs")
            for (key in expectedKeys) {
                if (key == "createdAt") {
                    assertTrue(actual.get(key) is Number, "$path.$key: expected a number timestamp, got ${actual.get(key)}")
                    continue
                }
                assertJsonEqualsIgnoringCreatedAt(expected.get(key), actual.get(key), "$path.$key")
            }
        }
        is JSONArray -> {
            assertTrue(actual is JSONArray, "$path: expected an array, got $actual")
            actual as JSONArray
            assertEquals(expected.length(), actual.length(), "$path: array length differs")
            for (i in 0 until expected.length()) {
                assertJsonEqualsIgnoringCreatedAt(expected.get(i), actual.get(i), "$path[$i]")
            }
        }
        else -> assertEquals(expected, actual, path)
    }
}

private fun assertMatchesGolden(fixtureBaseName: String, comments: List<PersistedComment>) {
    val expected = goldenComments("$fixtureBaseName.json")
    val actual = JSONArray(comments.map { it.toJson() })
    assertJsonEqualsIgnoringCreatedAt(expected, actual, fixtureBaseName)
}

class XlsxCommentsTest {

    // ── Golden parity against the REAL desktop reader's own output ─────────

    @Test
    fun q3SalesByRepMatchesTheDesktopReaderFieldForField() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("q3-sales-by-rep", result.comments)
    }

    // F2 (implementation review — parity): a workbook with one real worksheet
    // plus one CHARTSHEET must be labelled single-sheet, exactly like desktop
    // (exceljs's own `reconcile()` never surfaces a chartsheet as a worksheet
    // at all — xlsx-comments.ts's own header comment) — never counted as a
    // second "sheet" that would make the selector stamp a `sheet` name the
    // desktop reader would never stamp for the identical file. Golden parity
    // against the real desktop reader's own output for this exact fixture.
    @Test
    fun chartsheetWorkbookMatchesTheDesktopReaderFieldForFieldAndStaysSingleSheet() {
        val result = readXlsxComments(fixtureFile("chartsheet-workbook.xlsx"), "reports/chartsheet-workbook.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        assertMatchesGolden("chartsheet-workbook", result.comments)
        val comments = result.comments
        assertEquals(1, comments.size)
        val note = comments[0]
        val selector = note.selector
        assertTrue(selector is CommentSelector.Cell, "expected a cell selector")
        // §4.2: `sheet` is only ever named on a MULTI-sheet workbook — a
        // chartsheet counted as a second worksheet (the pre-fix bug this test
        // pins) would make this workbook wrongly look multi-sheet and stamp
        // "Data" here instead of leaving it unnamed.
        assertEquals(null, (selector as CommentSelector.Cell).selector.sheet)
    }

    // ── Behavioural pins mirroring desktop/tests/xlsx-comments.test.ts ─────

    @Test
    fun readsThePlainNoteOnTheFirstSheet() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B2" }
        assertTrue(note != null, "expected a note on B2")
        assertEquals("person:Priya Shah", note.author)
        assertTrue(note.text.contains("West is Priya"))
        assertEquals(false, note.resolved)
        assertTrue(note.replies.isEmpty())
        assertEquals("reports/q3-sales-by-rep.xlsx", note.path)
    }

    @Test
    fun findsANoteOnANonFirstSheetNamingThatSheetOnTheSelector() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B4" }
        assertTrue(note != null, "expected a note on B4")
        val selector = (note.selector as CommentSelector.Cell).selector
        assertEquals("By rep", selector.sheet)
        assertTrue(note.text.contains("North looks low for July"))
    }

    @Test
    fun doesNotMistakeTheFirstSheetForTheWholeWorkbookEightNotesTotal() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        assertEquals(8, result.comments.size)
    }

    @Test
    fun splitsAMultiTurnNoteIntoTheOriginalCommentPlusItsReplies() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val threaded = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B5" }
        assertTrue(threaded != null)
        assertEquals("person:Priya Shah", threaded.author)
        assertTrue(threaded.text.contains("Diego’s numbers look great"))
        assertEquals(1, threaded.replies.size)
        assertEquals("person:Marcus Lee", threaded.replies[0].author)
        assertTrue(threaded.replies[0].text.contains("Agreed"))
    }

    @Test
    fun readsTheResolveMarkerAsResolvedAndStripsItFromTheText() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val threaded = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B5" }
        assertTrue(threaded != null)
        assertEquals(true, threaded.resolved)
        assertTrue(!threaded.replies[0].text.contains("yc:resolved"))
        assertTrue(!threaded.replies[0].text.contains("​"))
    }

    @Test
    fun doesNotReadResolveLikeNaturalLanguageAsTheResolveMarker() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B2" }
        assertTrue(note != null, "expected a note on B2")
        assertEquals(false, note.resolved)
    }

    @Test
    fun findsItsNoteOnABorderedValueLessCell() {
        // Implementation-review F1's own shape, ported to the read path here
        // via direct comments.xml parsing rather than an eachRow/eachCell
        // traversal — since this reader drives off the comments PART
        // directly (never a cell-by-cell walk), it has no equivalent
        // "includeEmpty" pitfall to guard against at all (see XlsxComments.kt's
        // own header). This test proves the outcome either way: B18's note is
        // found despite the cell itself carrying no value in the fixture.
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B18" }
        assertTrue(note != null, "expected a note on B18")
        assertEquals("person:Priya Shah", note.author)
        assertTrue(note.text.contains("Reserved for the September actuals"))
        assertEquals(false, note.resolved)
    }

    @Test
    fun keepsTheFullTextOfAColonFreeForeignNoteWithANeutralAuthor() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B19" }
        assertTrue(note != null)
        assertEquals("person:Unknown", note.author)
        assertEquals("Diego mentioned this figure needs a second look before the board meeting.", note.text)
    }

    @Test
    fun doesNotMisreadAColonThatIsNotThisAppsOwnNameConvention() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B20" }
        assertTrue(note != null)
        assertEquals("person:Unknown", note.author)
        assertEquals("Check this number: 42 seems low for August.", note.text)
    }

    @Test
    fun readsTheLegacyBracketedTokenMarkerAsResolvedBackwardCompatibility() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B6" }
        assertTrue(note != null)
        assertEquals(true, note.resolved)
        assertTrue(!note.replies[0].text.contains("yc:resolved"))
    }

    @Test
    fun doesNotReadARealReplyEndingInPlainCheckmarkResolvedNoZwspAsResolved() {
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok, "expected Ok, got $result")
        val comments = result.comments
        val note = comments.find { it.selector is CommentSelector.Cell && it.selector.selector.cell == "B7" }
        assertTrue(note != null)
        assertEquals(false, note.resolved)
        assertEquals("Following up next week. ✓ Resolved", note.text)
    }

    @Test
    fun notAValidZipRefusesHonestlyInsteadOfThrowing() {
        val garbage = Files.createTempFile("ycd-xlsx-read-", "-garbage.xlsx").toFile()
        garbage.deleteOnExit()
        garbage.writeBytes("not a workbook".toByteArray(Charsets.UTF_8))
        val result = readXlsxComments(garbage, "reports/garbage.xlsx")
        assertEquals(XlsxReadResult.Err(XlsxReadError.INVALID_XLSX), result)
    }

    // F1 (implementation review — high, security): same reasoning as
    // DocxCommentsTest.kt's own identical pin — see `rejectDoctype`'s doc
    // comment (XlsxComments.kt) for why this platform-independent pre-check
    // exists on top of the factory's own (possibly Expat-ignored, on a real
    // device) `disallow-doctype-decl` feature.
    @Test
    fun refusesAWorkbookXmlCarryingAnInternalDtdEntityBomb() {
        val doctypeBomb = """
            <?xml version="1.0"?>
            <!DOCTYPE lolz [
             <!ENTITY lol "lol">
             <!ENTITY lol2 "&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;&lol;">
            ]>
            <workbook><sheets><sheet name="&lol2;" sheetId="1" r:id="rId1"/></sheets></workbook>
        """.trimIndent()
        val bytes = buildPlainZip(
            mapOf(
                "xl/workbook.xml" to doctypeBomb,
                "xl/_rels/workbook.xml.rels" to "<Relationships/>",
            ),
        )
        val f = Files.createTempFile("ycd-xlsx-read-", "-doctype-bomb.xlsx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readXlsxComments(f, "reports/doctype-bomb.xlsx")
        assertEquals(XlsxReadResult.Err(XlsxReadError.UNSAFE_XML), result)
    }

    // F3 (implementation review): same reasoning as DocxCommentsTest.kt's own
    // identical pin — a REAL zip bomb whose DECLARED size is patched down to a
    // few bytes (so the declared-size precheck alone would wave it through)
    // must still be refused once its real decompressed bytes cross the
    // ceiling, caught by `readEntryBounded`'s byte-counting loop, never by
    // trusting the archive's own metadata. The bomb sits at `xl/workbook.xml`
    // itself — the FIRST part `readXlsxComments` unconditionally reads — so
    // this exercises the real end-to-end read path, not just the primitive:
    // its actual (bogus, all-zero) content never needs to look like a real
    // workbook, since `readEntryBounded` throws mid-read, before this or any
    // other content is ever handed to `parseWorkbookSheets`.
    @Test
    fun refusesAWorkbookXmlEntryWhoseRealDecompressedBytesExceedTheCeilingEvenWhenItsDeclaredSizeIsTiny() {
        val bytes = buildRealZipBomb(
            files = emptyMap(),
            bombEntryName = "xl/workbook.xml",
            realUncompressedBytes = 201L * 1024 * 1024,
            declaredUncompressedSize = 10L,
        )
        val f = Files.createTempFile("ycd-xlsx-read-", "-real-bomb.xlsx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readXlsxComments(f, "reports/real-bomb.xlsx")
        assertEquals(XlsxReadResult.Err(XlsxReadError.ARCHIVE_TOO_LARGE), result)
    }

    @Test
    fun refusesAnArchiveDeclaringAnImplausibleUncompressedSize() {
        val bytes = buildDeclaredOversizeZip(
            mapOf(
                "xl/workbook.xml" to "<workbook/>",
                "xl/worksheets/sheet1.xml" to "<worksheet/>",
            ),
            "xl/worksheets/sheet1.xml",
            500L * 1024 * 1024,
        )
        val f = Files.createTempFile("ycd-xlsx-read-", "-bomb.xlsx").toFile()
        f.deleteOnExit()
        f.writeBytes(bytes)
        val result = readXlsxComments(f, "reports/bomb.xlsx")
        assertEquals(XlsxReadResult.Err(XlsxReadError.ARCHIVE_TOO_LARGE), result)
    }

    @Test
    fun runsInAPlainJvmEnvironmentNoAndroidFrameworkClassInvolved() {
        // Same pin as DocxCommentsTest.kt's own — reaching this assertion at
        // all under a plain `./gradlew test` invocation IS the pin.
        val result = readXlsxComments(fixtureFile("q3-sales-by-rep.xlsx"), "reports/q3-sales-by-rep.xlsx")
        assertTrue(result is XlsxReadResult.Ok)
    }
}
